// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetMeIdentityUsers
    {
        public static Task<GetMeIdentityUsersResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetMeIdentityUsersResult>("ovh:index/getMeIdentityUsers:getMeIdentityUsers", InvokeArgs.Empty, options.WithVersion());
    }


    [OutputType]
    public sealed class GetMeIdentityUsersResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Users;

        [OutputConstructor]
        private GetMeIdentityUsersResult(
            string id,

            ImmutableArray<string> users)
        {
            Id = id;
            Users = users;
        }
    }
}
