// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetOvh_Cloud_Project_Capabilities_Containerregistry_Filter
    {
        public static Task<GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterResult> InvokeAsync(GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterResult>("ovh:index/getOvh_Cloud_Project_Capabilities_Containerregistry_Filter:getOvh_Cloud_Project_Capabilities_Containerregistry_Filter", args ?? new GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterArgs(), options.WithVersion());
    }


    public sealed class GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterArgs : Pulumi.InvokeArgs
    {
        [Input("planName", required: true)]
        public string PlanName { get; set; } = null!;

        [Input("region", required: true)]
        public string Region { get; set; } = null!;

        [Input("serviceName", required: true)]
        public string ServiceName { get; set; } = null!;

        public GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterResult
    {
        public readonly string Code;
        public readonly string CreatedAt;
        public readonly ImmutableArray<Outputs.GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterFeatureResult> Features;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string PlanName;
        public readonly string Region;
        public readonly ImmutableArray<Outputs.GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterRegistryLimitResult> RegistryLimits;
        public readonly string ServiceName;
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterResult(
            string code,

            string createdAt,

            ImmutableArray<Outputs.GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterFeatureResult> features,

            string id,

            string name,

            string planName,

            string region,

            ImmutableArray<Outputs.GetOvh_Cloud_Project_Capabilities_Containerregistry_FilterRegistryLimitResult> registryLimits,

            string serviceName,

            string updatedAt)
        {
            Code = code;
            CreatedAt = createdAt;
            Features = features;
            Id = id;
            Name = name;
            PlanName = planName;
            Region = region;
            RegistryLimits = registryLimits;
            ServiceName = serviceName;
            UpdatedAt = updatedAt;
        }
    }
}
