// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetOvh_Me_Identity_User
    {
        public static Task<GetOvh_Me_Identity_UserResult> InvokeAsync(GetOvh_Me_Identity_UserArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetOvh_Me_Identity_UserResult>("ovh:index/getOvh_Me_Identity_User:getOvh_Me_Identity_User", args ?? new GetOvh_Me_Identity_UserArgs(), options.WithVersion());
    }


    public sealed class GetOvh_Me_Identity_UserArgs : Pulumi.InvokeArgs
    {
        [Input("user", required: true)]
        public string User { get; set; } = null!;

        public GetOvh_Me_Identity_UserArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetOvh_Me_Identity_UserResult
    {
        public readonly string Creation;
        public readonly string Description;
        public readonly string Email;
        public readonly string Group;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string LastUpdate;
        public readonly string Login;
        public readonly string PasswordLastUpdate;
        public readonly string Status;
        public readonly string User;

        [OutputConstructor]
        private GetOvh_Me_Identity_UserResult(
            string creation,

            string description,

            string email,

            string group,

            string id,

            string lastUpdate,

            string login,

            string passwordLastUpdate,

            string status,

            string user)
        {
            Creation = creation;
            Description = description;
            Email = email;
            Group = group;
            Id = id;
            LastUpdate = lastUpdate;
            Login = login;
            PasswordLastUpdate = passwordLastUpdate;
            Status = status;
            User = user;
        }
    }
}
