// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetOrderCartProductOptions
    {
        public static Task<GetOrderCartProductOptionsResult> InvokeAsync(GetOrderCartProductOptionsArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetOrderCartProductOptionsResult>("ovh:index/getOrderCartProductOptions:getOrderCartProductOptions", args ?? new GetOrderCartProductOptionsArgs(), options.WithVersion());
    }


    public sealed class GetOrderCartProductOptionsArgs : Pulumi.InvokeArgs
    {
        [Input("cartId", required: true)]
        public string CartId { get; set; } = null!;

        [Input("catalogName")]
        public string? CatalogName { get; set; }

        [Input("planCode", required: true)]
        public string PlanCode { get; set; } = null!;

        [Input("product", required: true)]
        public string Product { get; set; } = null!;

        public GetOrderCartProductOptionsArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetOrderCartProductOptionsResult
    {
        public readonly string CartId;
        public readonly string? CatalogName;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string PlanCode;
        public readonly string Product;
        public readonly ImmutableArray<Outputs.GetOrderCartProductOptionsResultResult> Results;

        [OutputConstructor]
        private GetOrderCartProductOptionsResult(
            string cartId,

            string? catalogName,

            string id,

            string planCode,

            string product,

            ImmutableArray<Outputs.GetOrderCartProductOptionsResultResult> results)
        {
            CartId = cartId;
            CatalogName = catalogName;
            Id = id;
            PlanCode = planCode;
            Product = product;
            Results = results;
        }
    }
}
