// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetOvh_Me_Paymentmean_Creditcard
    {
        public static Task<GetOvh_Me_Paymentmean_CreditcardResult> InvokeAsync(GetOvh_Me_Paymentmean_CreditcardArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetOvh_Me_Paymentmean_CreditcardResult>("ovh:index/getOvh_Me_Paymentmean_Creditcard:getOvh_Me_Paymentmean_Creditcard", args ?? new GetOvh_Me_Paymentmean_CreditcardArgs(), options.WithVersion());
    }


    public sealed class GetOvh_Me_Paymentmean_CreditcardArgs : Pulumi.InvokeArgs
    {
        [Input("descriptionRegexp")]
        public string? DescriptionRegexp { get; set; }

        [Input("states")]
        private List<string>? _states;
        public List<string> States
        {
            get => _states ?? (_states = new List<string>());
            set => _states = value;
        }

        [Input("useDefault")]
        public bool? UseDefault { get; set; }

        [Input("useLastToExpire")]
        public bool? UseLastToExpire { get; set; }

        public GetOvh_Me_Paymentmean_CreditcardArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetOvh_Me_Paymentmean_CreditcardResult
    {
        public readonly bool Default;
        public readonly string Description;
        public readonly string? DescriptionRegexp;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string State;
        public readonly ImmutableArray<string> States;
        public readonly bool? UseDefault;
        public readonly bool? UseLastToExpire;

        [OutputConstructor]
        private GetOvh_Me_Paymentmean_CreditcardResult(
            bool @default,

            string description,

            string? descriptionRegexp,

            string id,

            string state,

            ImmutableArray<string> states,

            bool? useDefault,

            bool? useLastToExpire)
        {
            Default = @default;
            Description = description;
            DescriptionRegexp = descriptionRegexp;
            Id = id;
            State = state;
            States = states;
            UseDefault = useDefault;
            UseLastToExpire = useLastToExpire;
        }
    }
}
