// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetOvh_Me_Ipxe_Script
    {
        public static Task<GetOvh_Me_Ipxe_ScriptResult> InvokeAsync(GetOvh_Me_Ipxe_ScriptArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetOvh_Me_Ipxe_ScriptResult>("ovh:index/getOvh_Me_Ipxe_Script:getOvh_Me_Ipxe_Script", args ?? new GetOvh_Me_Ipxe_ScriptArgs(), options.WithVersion());
    }


    public sealed class GetOvh_Me_Ipxe_ScriptArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetOvh_Me_Ipxe_ScriptArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetOvh_Me_Ipxe_ScriptResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string Script;

        [OutputConstructor]
        private GetOvh_Me_Ipxe_ScriptResult(
            string id,

            string name,

            string script)
        {
            Id = id;
            Name = name;
            Script = script;
        }
    }
}
