// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetOrderCartProductPlan
    {
        public static Task<GetOrderCartProductPlanResult> InvokeAsync(GetOrderCartProductPlanArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetOrderCartProductPlanResult>("ovh:index/getOrderCartProductPlan:getOrderCartProductPlan", args ?? new GetOrderCartProductPlanArgs(), options.WithVersion());
    }


    public sealed class GetOrderCartProductPlanArgs : Pulumi.InvokeArgs
    {
        [Input("cartId", required: true)]
        public string CartId { get; set; } = null!;

        [Input("catalogName")]
        public string? CatalogName { get; set; }

        [Input("planCode", required: true)]
        public string PlanCode { get; set; } = null!;

        [Input("priceCapacity", required: true)]
        public string PriceCapacity { get; set; } = null!;

        [Input("product", required: true)]
        public string Product { get; set; } = null!;

        public GetOrderCartProductPlanArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetOrderCartProductPlanResult
    {
        public readonly string CartId;
        public readonly string? CatalogName;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string PlanCode;
        public readonly string PriceCapacity;
        public readonly ImmutableArray<Outputs.GetOrderCartProductPlanPriceResult> Prices;
        public readonly string Product;
        public readonly string ProductName;
        public readonly string ProductType;
        public readonly ImmutableArray<Outputs.GetOrderCartProductPlanSelectedPriceResult> SelectedPrices;

        [OutputConstructor]
        private GetOrderCartProductPlanResult(
            string cartId,

            string? catalogName,

            string id,

            string planCode,

            string priceCapacity,

            ImmutableArray<Outputs.GetOrderCartProductPlanPriceResult> prices,

            string product,

            string productName,

            string productType,

            ImmutableArray<Outputs.GetOrderCartProductPlanSelectedPriceResult> selectedPrices)
        {
            CartId = cartId;
            CatalogName = catalogName;
            Id = id;
            PlanCode = planCode;
            PriceCapacity = priceCapacity;
            Prices = prices;
            Product = product;
            ProductName = productName;
            ProductType = productType;
            SelectedPrices = selectedPrices;
        }
    }
}
