// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    [OvhResourceType("ovh:index/iploadbalancingTcpFrontend:IploadbalancingTcpFrontend")]
    public partial class IploadbalancingTcpFrontend : Pulumi.CustomResource
    {
        [Output("allowedSources")]
        public Output<ImmutableArray<string>> AllowedSources { get; private set; } = null!;

        [Output("dedicatedIpfos")]
        public Output<ImmutableArray<string>> DedicatedIpfos { get; private set; } = null!;

        [Output("defaultFarmId")]
        public Output<int> DefaultFarmId { get; private set; } = null!;

        [Output("defaultSslId")]
        public Output<int> DefaultSslId { get; private set; } = null!;

        [Output("disabled")]
        public Output<bool?> Disabled { get; private set; } = null!;

        [Output("displayName")]
        public Output<string?> DisplayName { get; private set; } = null!;

        [Output("port")]
        public Output<string> Port { get; private set; } = null!;

        [Output("serviceName")]
        public Output<string> ServiceName { get; private set; } = null!;

        [Output("ssl")]
        public Output<bool?> Ssl { get; private set; } = null!;

        [Output("zone")]
        public Output<string> Zone { get; private set; } = null!;


        /// <summary>
        /// Create a IploadbalancingTcpFrontend resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IploadbalancingTcpFrontend(string name, IploadbalancingTcpFrontendArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/iploadbalancingTcpFrontend:IploadbalancingTcpFrontend", name, args ?? new IploadbalancingTcpFrontendArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IploadbalancingTcpFrontend(string name, Input<string> id, IploadbalancingTcpFrontendState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/iploadbalancingTcpFrontend:IploadbalancingTcpFrontend", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IploadbalancingTcpFrontend resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IploadbalancingTcpFrontend Get(string name, Input<string> id, IploadbalancingTcpFrontendState? state = null, CustomResourceOptions? options = null)
        {
            return new IploadbalancingTcpFrontend(name, id, state, options);
        }
    }

    public sealed class IploadbalancingTcpFrontendArgs : Pulumi.ResourceArgs
    {
        [Input("allowedSources")]
        private InputList<string>? _allowedSources;
        public InputList<string> AllowedSources
        {
            get => _allowedSources ?? (_allowedSources = new InputList<string>());
            set => _allowedSources = value;
        }

        [Input("dedicatedIpfos")]
        private InputList<string>? _dedicatedIpfos;
        public InputList<string> DedicatedIpfos
        {
            get => _dedicatedIpfos ?? (_dedicatedIpfos = new InputList<string>());
            set => _dedicatedIpfos = value;
        }

        [Input("defaultFarmId")]
        public Input<int>? DefaultFarmId { get; set; }

        [Input("defaultSslId")]
        public Input<int>? DefaultSslId { get; set; }

        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        [Input("port", required: true)]
        public Input<string> Port { get; set; } = null!;

        [Input("serviceName", required: true)]
        public Input<string> ServiceName { get; set; } = null!;

        [Input("ssl")]
        public Input<bool>? Ssl { get; set; }

        [Input("zone", required: true)]
        public Input<string> Zone { get; set; } = null!;

        public IploadbalancingTcpFrontendArgs()
        {
        }
    }

    public sealed class IploadbalancingTcpFrontendState : Pulumi.ResourceArgs
    {
        [Input("allowedSources")]
        private InputList<string>? _allowedSources;
        public InputList<string> AllowedSources
        {
            get => _allowedSources ?? (_allowedSources = new InputList<string>());
            set => _allowedSources = value;
        }

        [Input("dedicatedIpfos")]
        private InputList<string>? _dedicatedIpfos;
        public InputList<string> DedicatedIpfos
        {
            get => _dedicatedIpfos ?? (_dedicatedIpfos = new InputList<string>());
            set => _dedicatedIpfos = value;
        }

        [Input("defaultFarmId")]
        public Input<int>? DefaultFarmId { get; set; }

        [Input("defaultSslId")]
        public Input<int>? DefaultSslId { get; set; }

        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        [Input("port")]
        public Input<string>? Port { get; set; }

        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        [Input("ssl")]
        public Input<bool>? Ssl { get; set; }

        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public IploadbalancingTcpFrontendState()
        {
        }
    }
}
