// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    [OvhResourceType("ovh:index/ovh_iploadbalancing_tcp_farm_server:ovh_iploadbalancing_tcp_farm_server")]
    public partial class Ovh_iploadbalancing_tcp_farm_server : Pulumi.CustomResource
    {
        [Output("address")]
        public Output<string> Address { get; private set; } = null!;

        [Output("backup")]
        public Output<bool?> Backup { get; private set; } = null!;

        [Output("chain")]
        public Output<string?> Chain { get; private set; } = null!;

        [Output("displayName")]
        public Output<string?> DisplayName { get; private set; } = null!;

        [Output("farmId")]
        public Output<int> FarmId { get; private set; } = null!;

        [Output("port")]
        public Output<int?> Port { get; private set; } = null!;

        [Output("probe")]
        public Output<bool?> Probe { get; private set; } = null!;

        [Output("proxyProtocolVersion")]
        public Output<string?> ProxyProtocolVersion { get; private set; } = null!;

        [Output("serviceName")]
        public Output<string> ServiceName { get; private set; } = null!;

        [Output("ssl")]
        public Output<bool?> Ssl { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("weight")]
        public Output<int?> Weight { get; private set; } = null!;


        /// <summary>
        /// Create a Ovh_iploadbalancing_tcp_farm_server resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Ovh_iploadbalancing_tcp_farm_server(string name, Ovh_iploadbalancing_tcp_farm_serverArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/ovh_iploadbalancing_tcp_farm_server:ovh_iploadbalancing_tcp_farm_server", name, args ?? new Ovh_iploadbalancing_tcp_farm_serverArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Ovh_iploadbalancing_tcp_farm_server(string name, Input<string> id, Ovh_iploadbalancing_tcp_farm_serverState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/ovh_iploadbalancing_tcp_farm_server:ovh_iploadbalancing_tcp_farm_server", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Ovh_iploadbalancing_tcp_farm_server resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Ovh_iploadbalancing_tcp_farm_server Get(string name, Input<string> id, Ovh_iploadbalancing_tcp_farm_serverState? state = null, CustomResourceOptions? options = null)
        {
            return new Ovh_iploadbalancing_tcp_farm_server(name, id, state, options);
        }
    }

    public sealed class Ovh_iploadbalancing_tcp_farm_serverArgs : Pulumi.ResourceArgs
    {
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        [Input("backup")]
        public Input<bool>? Backup { get; set; }

        [Input("chain")]
        public Input<string>? Chain { get; set; }

        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        [Input("farmId", required: true)]
        public Input<int> FarmId { get; set; } = null!;

        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("probe")]
        public Input<bool>? Probe { get; set; }

        [Input("proxyProtocolVersion")]
        public Input<string>? ProxyProtocolVersion { get; set; }

        [Input("serviceName", required: true)]
        public Input<string> ServiceName { get; set; } = null!;

        [Input("ssl")]
        public Input<bool>? Ssl { get; set; }

        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public Ovh_iploadbalancing_tcp_farm_serverArgs()
        {
        }
    }

    public sealed class Ovh_iploadbalancing_tcp_farm_serverState : Pulumi.ResourceArgs
    {
        [Input("address")]
        public Input<string>? Address { get; set; }

        [Input("backup")]
        public Input<bool>? Backup { get; set; }

        [Input("chain")]
        public Input<string>? Chain { get; set; }

        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        [Input("farmId")]
        public Input<int>? FarmId { get; set; }

        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("probe")]
        public Input<bool>? Probe { get; set; }

        [Input("proxyProtocolVersion")]
        public Input<string>? ProxyProtocolVersion { get; set; }

        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        [Input("ssl")]
        public Input<bool>? Ssl { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public Ovh_iploadbalancing_tcp_farm_serverState()
        {
        }
    }
}
