// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    [OvhResourceType("ovh:index/ovh_cloud_project:ovh_cloud_project")]
    public partial class Ovh_cloud_project : Pulumi.CustomResource
    {
        [Output("access")]
        public Output<string> Access { get; private set; } = null!;

        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Details about an Order
        /// </summary>
        [Output("orders")]
        public Output<ImmutableArray<Outputs.Ovh_cloud_projectOrder>> Orders { get; private set; } = null!;

        /// <summary>
        /// Ovh Subsidiary
        /// </summary>
        [Output("ovhSubsidiary")]
        public Output<string> OvhSubsidiary { get; private set; } = null!;

        /// <summary>
        /// Ovh payment mode
        /// </summary>
        [Output("paymentMean")]
        public Output<string> PaymentMean { get; private set; } = null!;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        [Output("plan")]
        public Output<Outputs.Ovh_cloud_projectPlan> Plan { get; private set; } = null!;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        [Output("planOptions")]
        public Output<ImmutableArray<Outputs.Ovh_cloud_projectPlanOption>> PlanOptions { get; private set; } = null!;

        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        [Output("projectName")]
        public Output<string> ProjectName { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;


        /// <summary>
        /// Create a Ovh_cloud_project resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Ovh_cloud_project(string name, Ovh_cloud_projectArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/ovh_cloud_project:ovh_cloud_project", name, args ?? new Ovh_cloud_projectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Ovh_cloud_project(string name, Input<string> id, Ovh_cloud_projectState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/ovh_cloud_project:ovh_cloud_project", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Ovh_cloud_project resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Ovh_cloud_project Get(string name, Input<string> id, Ovh_cloud_projectState? state = null, CustomResourceOptions? options = null)
        {
            return new Ovh_cloud_project(name, id, state, options);
        }
    }

    public sealed class Ovh_cloud_projectArgs : Pulumi.ResourceArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Ovh Subsidiary
        /// </summary>
        [Input("ovhSubsidiary", required: true)]
        public Input<string> OvhSubsidiary { get; set; } = null!;

        /// <summary>
        /// Ovh payment mode
        /// </summary>
        [Input("paymentMean", required: true)]
        public Input<string> PaymentMean { get; set; } = null!;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        [Input("plan", required: true)]
        public Input<Inputs.Ovh_cloud_projectPlanArgs> Plan { get; set; } = null!;

        [Input("planOptions")]
        private InputList<Inputs.Ovh_cloud_projectPlanOptionArgs>? _planOptions;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        public InputList<Inputs.Ovh_cloud_projectPlanOptionArgs> PlanOptions
        {
            get => _planOptions ?? (_planOptions = new InputList<Inputs.Ovh_cloud_projectPlanOptionArgs>());
            set => _planOptions = value;
        }

        public Ovh_cloud_projectArgs()
        {
        }
    }

    public sealed class Ovh_cloud_projectState : Pulumi.ResourceArgs
    {
        [Input("access")]
        public Input<string>? Access { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("orders")]
        private InputList<Inputs.Ovh_cloud_projectOrderGetArgs>? _orders;

        /// <summary>
        /// Details about an Order
        /// </summary>
        public InputList<Inputs.Ovh_cloud_projectOrderGetArgs> Orders
        {
            get => _orders ?? (_orders = new InputList<Inputs.Ovh_cloud_projectOrderGetArgs>());
            set => _orders = value;
        }

        /// <summary>
        /// Ovh Subsidiary
        /// </summary>
        [Input("ovhSubsidiary")]
        public Input<string>? OvhSubsidiary { get; set; }

        /// <summary>
        /// Ovh payment mode
        /// </summary>
        [Input("paymentMean")]
        public Input<string>? PaymentMean { get; set; }

        /// <summary>
        /// Product Plan to order
        /// </summary>
        [Input("plan")]
        public Input<Inputs.Ovh_cloud_projectPlanGetArgs>? Plan { get; set; }

        [Input("planOptions")]
        private InputList<Inputs.Ovh_cloud_projectPlanOptionGetArgs>? _planOptions;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        public InputList<Inputs.Ovh_cloud_projectPlanOptionGetArgs> PlanOptions
        {
            get => _planOptions ?? (_planOptions = new InputList<Inputs.Ovh_cloud_projectPlanOptionGetArgs>());
            set => _planOptions = value;
        }

        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        [Input("projectName")]
        public Input<string>? ProjectName { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        public Ovh_cloud_projectState()
        {
        }
    }
}
