// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    [OvhResourceType("ovh:index/ovh_me_ssh_key:ovh_me_ssh_key")]
    public partial class Ovh_me_ssh_key : Pulumi.CustomResource
    {
        /// <summary>
        /// True when this public Ssh key is used for rescue mode and reinstallations
        /// </summary>
        [Output("default")]
        public Output<bool> Default { get; private set; } = null!;

        /// <summary>
        /// ASCII encoded public Ssh key
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// Name of this public Ssh key
        /// </summary>
        [Output("keyName")]
        public Output<string> KeyName { get; private set; } = null!;


        /// <summary>
        /// Create a Ovh_me_ssh_key resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Ovh_me_ssh_key(string name, Ovh_me_ssh_keyArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/ovh_me_ssh_key:ovh_me_ssh_key", name, args ?? new Ovh_me_ssh_keyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Ovh_me_ssh_key(string name, Input<string> id, Ovh_me_ssh_keyState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/ovh_me_ssh_key:ovh_me_ssh_key", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Ovh_me_ssh_key resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Ovh_me_ssh_key Get(string name, Input<string> id, Ovh_me_ssh_keyState? state = null, CustomResourceOptions? options = null)
        {
            return new Ovh_me_ssh_key(name, id, state, options);
        }
    }

    public sealed class Ovh_me_ssh_keyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// True when this public Ssh key is used for rescue mode and reinstallations
        /// </summary>
        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// ASCII encoded public Ssh key
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// Name of this public Ssh key
        /// </summary>
        [Input("keyName", required: true)]
        public Input<string> KeyName { get; set; } = null!;

        public Ovh_me_ssh_keyArgs()
        {
        }
    }

    public sealed class Ovh_me_ssh_keyState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// True when this public Ssh key is used for rescue mode and reinstallations
        /// </summary>
        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// ASCII encoded public Ssh key
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Name of this public Ssh key
        /// </summary>
        [Input("keyName")]
        public Input<string>? KeyName { get; set; }

        public Ovh_me_ssh_keyState()
        {
        }
    }
}
