// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    [OvhResourceType("ovh:index/ovh_cloud_project_network_private:ovh_cloud_project_network_private")]
    public partial class Ovh_cloud_project_network_private : Pulumi.CustomResource
    {
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("regions")]
        public Output<ImmutableArray<string>> Regions { get; private set; } = null!;

        [Output("regionsAttributes")]
        public Output<ImmutableArray<Outputs.Ovh_cloud_project_network_privateRegionsAttribute>> RegionsAttributes { get; private set; } = null!;

        [Output("regionsStatuses")]
        public Output<ImmutableArray<Outputs.Ovh_cloud_project_network_privateRegionsStatus>> RegionsStatuses { get; private set; } = null!;

        /// <summary>
        /// Service name of the resource representing the id of the cloud project.
        /// </summary>
        [Output("serviceName")]
        public Output<string> ServiceName { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        [Output("vlanId")]
        public Output<int?> VlanId { get; private set; } = null!;


        /// <summary>
        /// Create a Ovh_cloud_project_network_private resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Ovh_cloud_project_network_private(string name, Ovh_cloud_project_network_privateArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/ovh_cloud_project_network_private:ovh_cloud_project_network_private", name, args ?? new Ovh_cloud_project_network_privateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Ovh_cloud_project_network_private(string name, Input<string> id, Ovh_cloud_project_network_privateState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/ovh_cloud_project_network_private:ovh_cloud_project_network_private", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Ovh_cloud_project_network_private resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Ovh_cloud_project_network_private Get(string name, Input<string> id, Ovh_cloud_project_network_privateState? state = null, CustomResourceOptions? options = null)
        {
            return new Ovh_cloud_project_network_private(name, id, state, options);
        }
    }

    public sealed class Ovh_cloud_project_network_privateArgs : Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("regions")]
        private InputList<string>? _regions;
        [Obsolete(@"use the regions_attributes field instead")]
        public InputList<string> Regions
        {
            get => _regions ?? (_regions = new InputList<string>());
            set => _regions = value;
        }

        /// <summary>
        /// Service name of the resource representing the id of the cloud project.
        /// </summary>
        [Input("serviceName", required: true)]
        public Input<string> ServiceName { get; set; } = null!;

        [Input("vlanId")]
        public Input<int>? VlanId { get; set; }

        public Ovh_cloud_project_network_privateArgs()
        {
        }
    }

    public sealed class Ovh_cloud_project_network_privateState : Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("regions")]
        private InputList<string>? _regions;
        [Obsolete(@"use the regions_attributes field instead")]
        public InputList<string> Regions
        {
            get => _regions ?? (_regions = new InputList<string>());
            set => _regions = value;
        }

        [Input("regionsAttributes")]
        private InputList<Inputs.Ovh_cloud_project_network_privateRegionsAttributeGetArgs>? _regionsAttributes;
        public InputList<Inputs.Ovh_cloud_project_network_privateRegionsAttributeGetArgs> RegionsAttributes
        {
            get => _regionsAttributes ?? (_regionsAttributes = new InputList<Inputs.Ovh_cloud_project_network_privateRegionsAttributeGetArgs>());
            set => _regionsAttributes = value;
        }

        [Input("regionsStatuses")]
        private InputList<Inputs.Ovh_cloud_project_network_privateRegionsStatusGetArgs>? _regionsStatuses;
        [Obsolete(@"use the regions_attributes field instead")]
        public InputList<Inputs.Ovh_cloud_project_network_privateRegionsStatusGetArgs> RegionsStatuses
        {
            get => _regionsStatuses ?? (_regionsStatuses = new InputList<Inputs.Ovh_cloud_project_network_privateRegionsStatusGetArgs>());
            set => _regionsStatuses = value;
        }

        /// <summary>
        /// Service name of the resource representing the id of the cloud project.
        /// </summary>
        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("vlanId")]
        public Input<int>? VlanId { get; set; }

        public Ovh_cloud_project_network_privateState()
        {
        }
    }
}
