// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCloudProjectCapabilitiesContainerregistry(ctx *pulumi.Context, args *GetCloudProjectCapabilitiesContainerregistryArgs, opts ...pulumi.InvokeOption) (*GetCloudProjectCapabilitiesContainerregistryResult, error) {
	var rv GetCloudProjectCapabilitiesContainerregistryResult
	err := ctx.Invoke("ovh:index/getCloudProjectCapabilitiesContainerregistry:getCloudProjectCapabilitiesContainerregistry", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectCapabilitiesContainerregistry.
type GetCloudProjectCapabilitiesContainerregistryArgs struct {
	ServiceName string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectCapabilitiesContainerregistry.
type GetCloudProjectCapabilitiesContainerregistryResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id          string                                               `pulumi:"id"`
	Results     []GetCloudProjectCapabilitiesContainerregistryResult `pulumi:"results"`
	ServiceName string                                               `pulumi:"serviceName"`
}

func GetCloudProjectCapabilitiesContainerregistryOutput(ctx *pulumi.Context, args GetCloudProjectCapabilitiesContainerregistryOutputArgs, opts ...pulumi.InvokeOption) GetCloudProjectCapabilitiesContainerregistryResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCloudProjectCapabilitiesContainerregistryResult, error) {
			args := v.(GetCloudProjectCapabilitiesContainerregistryArgs)
			r, err := GetCloudProjectCapabilitiesContainerregistry(ctx, &args, opts...)
			return *r, err
		}).(GetCloudProjectCapabilitiesContainerregistryResultOutput)
}

// A collection of arguments for invoking getCloudProjectCapabilitiesContainerregistry.
type GetCloudProjectCapabilitiesContainerregistryOutputArgs struct {
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
}

func (GetCloudProjectCapabilitiesContainerregistryOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectCapabilitiesContainerregistryArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectCapabilitiesContainerregistry.
type GetCloudProjectCapabilitiesContainerregistryResultOutput struct{ *pulumi.OutputState }

func (GetCloudProjectCapabilitiesContainerregistryResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectCapabilitiesContainerregistryResult)(nil)).Elem()
}

func (o GetCloudProjectCapabilitiesContainerregistryResultOutput) ToGetCloudProjectCapabilitiesContainerregistryResultOutput() GetCloudProjectCapabilitiesContainerregistryResultOutput {
	return o
}

func (o GetCloudProjectCapabilitiesContainerregistryResultOutput) ToGetCloudProjectCapabilitiesContainerregistryResultOutputWithContext(ctx context.Context) GetCloudProjectCapabilitiesContainerregistryResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetCloudProjectCapabilitiesContainerregistryResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryResultOutput) Results() GetCloudProjectCapabilitiesContainerregistryResultArrayOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryResult) []GetCloudProjectCapabilitiesContainerregistryResult {
		return v.Results
	}).(GetCloudProjectCapabilitiesContainerregistryResultArrayOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCloudProjectCapabilitiesContainerregistryResultOutput{})
}
