// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCloudProjectContainerregistries(ctx *pulumi.Context, args *GetCloudProjectContainerregistriesArgs, opts ...pulumi.InvokeOption) (*GetCloudProjectContainerregistriesResult, error) {
	var rv GetCloudProjectContainerregistriesResult
	err := ctx.Invoke("ovh:index/getCloudProjectContainerregistries:getCloudProjectContainerregistries", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectContainerregistries.
type GetCloudProjectContainerregistriesArgs struct {
	ServiceName string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectContainerregistries.
type GetCloudProjectContainerregistriesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id          string                                     `pulumi:"id"`
	Results     []GetCloudProjectContainerregistriesResult `pulumi:"results"`
	ServiceName string                                     `pulumi:"serviceName"`
}

func GetCloudProjectContainerregistriesOutput(ctx *pulumi.Context, args GetCloudProjectContainerregistriesOutputArgs, opts ...pulumi.InvokeOption) GetCloudProjectContainerregistriesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCloudProjectContainerregistriesResult, error) {
			args := v.(GetCloudProjectContainerregistriesArgs)
			r, err := GetCloudProjectContainerregistries(ctx, &args, opts...)
			return *r, err
		}).(GetCloudProjectContainerregistriesResultOutput)
}

// A collection of arguments for invoking getCloudProjectContainerregistries.
type GetCloudProjectContainerregistriesOutputArgs struct {
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
}

func (GetCloudProjectContainerregistriesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectContainerregistriesArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectContainerregistries.
type GetCloudProjectContainerregistriesResultOutput struct{ *pulumi.OutputState }

func (GetCloudProjectContainerregistriesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectContainerregistriesResult)(nil)).Elem()
}

func (o GetCloudProjectContainerregistriesResultOutput) ToGetCloudProjectContainerregistriesResultOutput() GetCloudProjectContainerregistriesResultOutput {
	return o
}

func (o GetCloudProjectContainerregistriesResultOutput) ToGetCloudProjectContainerregistriesResultOutputWithContext(ctx context.Context) GetCloudProjectContainerregistriesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetCloudProjectContainerregistriesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectContainerregistriesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCloudProjectContainerregistriesResultOutput) Results() GetCloudProjectContainerregistriesResultArrayOutput {
	return o.ApplyT(func(v GetCloudProjectContainerregistriesResult) []GetCloudProjectContainerregistriesResult {
		return v.Results
	}).(GetCloudProjectContainerregistriesResultArrayOutput)
}

func (o GetCloudProjectContainerregistriesResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectContainerregistriesResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCloudProjectContainerregistriesResultOutput{})
}
