// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCloudProjectCapabilitiesContainerregistryFilter(ctx *pulumi.Context, args *GetCloudProjectCapabilitiesContainerregistryFilterArgs, opts ...pulumi.InvokeOption) (*GetCloudProjectCapabilitiesContainerregistryFilterResult, error) {
	var rv GetCloudProjectCapabilitiesContainerregistryFilterResult
	err := ctx.Invoke("ovh:index/getCloudProjectCapabilitiesContainerregistryFilter:getCloudProjectCapabilitiesContainerregistryFilter", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectCapabilitiesContainerregistryFilter.
type GetCloudProjectCapabilitiesContainerregistryFilterArgs struct {
	PlanName    string `pulumi:"planName"`
	Region      string `pulumi:"region"`
	ServiceName string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectCapabilitiesContainerregistryFilter.
type GetCloudProjectCapabilitiesContainerregistryFilterResult struct {
	Code      string                                                      `pulumi:"code"`
	CreatedAt string                                                      `pulumi:"createdAt"`
	Features  []GetCloudProjectCapabilitiesContainerregistryFilterFeature `pulumi:"features"`
	// The provider-assigned unique ID for this managed resource.
	Id             string                                                            `pulumi:"id"`
	Name           string                                                            `pulumi:"name"`
	PlanName       string                                                            `pulumi:"planName"`
	Region         string                                                            `pulumi:"region"`
	RegistryLimits []GetCloudProjectCapabilitiesContainerregistryFilterRegistryLimit `pulumi:"registryLimits"`
	ServiceName    string                                                            `pulumi:"serviceName"`
	UpdatedAt      string                                                            `pulumi:"updatedAt"`
}

func GetCloudProjectCapabilitiesContainerregistryFilterOutput(ctx *pulumi.Context, args GetCloudProjectCapabilitiesContainerregistryFilterOutputArgs, opts ...pulumi.InvokeOption) GetCloudProjectCapabilitiesContainerregistryFilterResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCloudProjectCapabilitiesContainerregistryFilterResult, error) {
			args := v.(GetCloudProjectCapabilitiesContainerregistryFilterArgs)
			r, err := GetCloudProjectCapabilitiesContainerregistryFilter(ctx, &args, opts...)
			return *r, err
		}).(GetCloudProjectCapabilitiesContainerregistryFilterResultOutput)
}

// A collection of arguments for invoking getCloudProjectCapabilitiesContainerregistryFilter.
type GetCloudProjectCapabilitiesContainerregistryFilterOutputArgs struct {
	PlanName    pulumi.StringInput `pulumi:"planName"`
	Region      pulumi.StringInput `pulumi:"region"`
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
}

func (GetCloudProjectCapabilitiesContainerregistryFilterOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectCapabilitiesContainerregistryFilterArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectCapabilitiesContainerregistryFilter.
type GetCloudProjectCapabilitiesContainerregistryFilterResultOutput struct{ *pulumi.OutputState }

func (GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectCapabilitiesContainerregistryFilterResult)(nil)).Elem()
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) ToGetCloudProjectCapabilitiesContainerregistryFilterResultOutput() GetCloudProjectCapabilitiesContainerregistryFilterResultOutput {
	return o
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) ToGetCloudProjectCapabilitiesContainerregistryFilterResultOutputWithContext(ctx context.Context) GetCloudProjectCapabilitiesContainerregistryFilterResultOutput {
	return o
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) Code() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) string { return v.Code }).(pulumi.StringOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) Features() GetCloudProjectCapabilitiesContainerregistryFilterFeatureArrayOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) []GetCloudProjectCapabilitiesContainerregistryFilterFeature {
		return v.Features
	}).(GetCloudProjectCapabilitiesContainerregistryFilterFeatureArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) PlanName() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) string { return v.PlanName }).(pulumi.StringOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) RegistryLimits() GetCloudProjectCapabilitiesContainerregistryFilterRegistryLimitArrayOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) []GetCloudProjectCapabilitiesContainerregistryFilterRegistryLimit {
		return v.RegistryLimits
	}).(GetCloudProjectCapabilitiesContainerregistryFilterRegistryLimitArrayOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o GetCloudProjectCapabilitiesContainerregistryFilterResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectCapabilitiesContainerregistryFilterResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCloudProjectCapabilitiesContainerregistryFilterResultOutput{})
}
