// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDedicatedInstallationTemplates(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetDedicatedInstallationTemplatesResult, error) {
	var rv GetDedicatedInstallationTemplatesResult
	err := ctx.Invoke("ovh:index/getDedicatedInstallationTemplates:getDedicatedInstallationTemplates", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDedicatedInstallationTemplates.
type GetDedicatedInstallationTemplatesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id      string   `pulumi:"id"`
	Results []string `pulumi:"results"`
}
