// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupMeIpxeScript(ctx *pulumi.Context, args *LookupMeIpxeScriptArgs, opts ...pulumi.InvokeOption) (*LookupMeIpxeScriptResult, error) {
	var rv LookupMeIpxeScriptResult
	err := ctx.Invoke("ovh:index/getMeIpxeScript:getMeIpxeScript", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMeIpxeScript.
type LookupMeIpxeScriptArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getMeIpxeScript.
type LookupMeIpxeScriptResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id     string `pulumi:"id"`
	Name   string `pulumi:"name"`
	Script string `pulumi:"script"`
}

func LookupMeIpxeScriptOutput(ctx *pulumi.Context, args LookupMeIpxeScriptOutputArgs, opts ...pulumi.InvokeOption) LookupMeIpxeScriptResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupMeIpxeScriptResult, error) {
			args := v.(LookupMeIpxeScriptArgs)
			r, err := LookupMeIpxeScript(ctx, &args, opts...)
			return *r, err
		}).(LookupMeIpxeScriptResultOutput)
}

// A collection of arguments for invoking getMeIpxeScript.
type LookupMeIpxeScriptOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupMeIpxeScriptOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMeIpxeScriptArgs)(nil)).Elem()
}

// A collection of values returned by getMeIpxeScript.
type LookupMeIpxeScriptResultOutput struct{ *pulumi.OutputState }

func (LookupMeIpxeScriptResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMeIpxeScriptResult)(nil)).Elem()
}

func (o LookupMeIpxeScriptResultOutput) ToLookupMeIpxeScriptResultOutput() LookupMeIpxeScriptResultOutput {
	return o
}

func (o LookupMeIpxeScriptResultOutput) ToLookupMeIpxeScriptResultOutputWithContext(ctx context.Context) LookupMeIpxeScriptResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupMeIpxeScriptResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIpxeScriptResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupMeIpxeScriptResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIpxeScriptResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupMeIpxeScriptResultOutput) Script() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIpxeScriptResult) string { return v.Script }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMeIpxeScriptResultOutput{})
}
