// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetOvh_Me_Installation_Template(ctx *pulumi.Context, args *GetOvh_Me_Installation_TemplateArgs, opts ...pulumi.InvokeOption) (*GetOvh_Me_Installation_TemplateResult, error) {
	var rv GetOvh_Me_Installation_TemplateResult
	err := ctx.Invoke("ovh:index/getOvh_Me_Installation_Template:getOvh_Me_Installation_Template", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOvh_Me_Installation_Template.
type GetOvh_Me_Installation_TemplateArgs struct {
	TemplateName string `pulumi:"templateName"`
}

// A collection of values returned by getOvh_Me_Installation_Template.
type GetOvh_Me_Installation_TemplateResult struct {
	AvailableLanguages    []string                                       `pulumi:"availableLanguages"`
	Beta                  bool                                           `pulumi:"beta"`
	BitFormat             int                                            `pulumi:"bitFormat"`
	Category              string                                         `pulumi:"category"`
	Customizations        []GetOvh_Me_Installation_TemplateCustomization `pulumi:"customizations"`
	DefaultLanguage       string                                         `pulumi:"defaultLanguage"`
	Deprecated            bool                                           `pulumi:"deprecated"`
	Description           string                                         `pulumi:"description"`
	Distribution          string                                         `pulumi:"distribution"`
	Family                string                                         `pulumi:"family"`
	Filesystems           []string                                       `pulumi:"filesystems"`
	HardRaidConfiguration bool                                           `pulumi:"hardRaidConfiguration"`
	// The provider-assigned unique ID for this managed resource.
	Id                         string                                           `pulumi:"id"`
	LastModification           string                                           `pulumi:"lastModification"`
	LvmReady                   bool                                             `pulumi:"lvmReady"`
	PartitionSchemes           []GetOvh_Me_Installation_TemplatePartitionScheme `pulumi:"partitionSchemes"`
	SupportsDistributionKernel bool                                             `pulumi:"supportsDistributionKernel"`
	SupportsGptLabel           bool                                             `pulumi:"supportsGptLabel"`
	SupportsRtm                bool                                             `pulumi:"supportsRtm"`
	SupportsSqlServer          bool                                             `pulumi:"supportsSqlServer"`
	SupportsUefi               string                                           `pulumi:"supportsUefi"`
	TemplateName               string                                           `pulumi:"templateName"`
}

func GetOvh_Me_Installation_TemplateOutput(ctx *pulumi.Context, args GetOvh_Me_Installation_TemplateOutputArgs, opts ...pulumi.InvokeOption) GetOvh_Me_Installation_TemplateResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOvh_Me_Installation_TemplateResult, error) {
			args := v.(GetOvh_Me_Installation_TemplateArgs)
			r, err := GetOvh_Me_Installation_Template(ctx, &args, opts...)
			return *r, err
		}).(GetOvh_Me_Installation_TemplateResultOutput)
}

// A collection of arguments for invoking getOvh_Me_Installation_Template.
type GetOvh_Me_Installation_TemplateOutputArgs struct {
	TemplateName pulumi.StringInput `pulumi:"templateName"`
}

func (GetOvh_Me_Installation_TemplateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Me_Installation_TemplateArgs)(nil)).Elem()
}

// A collection of values returned by getOvh_Me_Installation_Template.
type GetOvh_Me_Installation_TemplateResultOutput struct{ *pulumi.OutputState }

func (GetOvh_Me_Installation_TemplateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Me_Installation_TemplateResult)(nil)).Elem()
}

func (o GetOvh_Me_Installation_TemplateResultOutput) ToGetOvh_Me_Installation_TemplateResultOutput() GetOvh_Me_Installation_TemplateResultOutput {
	return o
}

func (o GetOvh_Me_Installation_TemplateResultOutput) ToGetOvh_Me_Installation_TemplateResultOutputWithContext(ctx context.Context) GetOvh_Me_Installation_TemplateResultOutput {
	return o
}

func (o GetOvh_Me_Installation_TemplateResultOutput) AvailableLanguages() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) []string { return v.AvailableLanguages }).(pulumi.StringArrayOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) Beta() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) bool { return v.Beta }).(pulumi.BoolOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) BitFormat() pulumi.IntOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) int { return v.BitFormat }).(pulumi.IntOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) Category() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.Category }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) Customizations() GetOvh_Me_Installation_TemplateCustomizationArrayOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) []GetOvh_Me_Installation_TemplateCustomization {
		return v.Customizations
	}).(GetOvh_Me_Installation_TemplateCustomizationArrayOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) DefaultLanguage() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.DefaultLanguage }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) Deprecated() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) bool { return v.Deprecated }).(pulumi.BoolOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) Distribution() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.Distribution }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) Family() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.Family }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) Filesystems() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) []string { return v.Filesystems }).(pulumi.StringArrayOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) HardRaidConfiguration() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) bool { return v.HardRaidConfiguration }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetOvh_Me_Installation_TemplateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) LastModification() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.LastModification }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) LvmReady() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) bool { return v.LvmReady }).(pulumi.BoolOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) PartitionSchemes() GetOvh_Me_Installation_TemplatePartitionSchemeArrayOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) []GetOvh_Me_Installation_TemplatePartitionScheme {
		return v.PartitionSchemes
	}).(GetOvh_Me_Installation_TemplatePartitionSchemeArrayOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) SupportsDistributionKernel() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) bool { return v.SupportsDistributionKernel }).(pulumi.BoolOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) SupportsGptLabel() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) bool { return v.SupportsGptLabel }).(pulumi.BoolOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) SupportsRtm() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) bool { return v.SupportsRtm }).(pulumi.BoolOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) SupportsSqlServer() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) bool { return v.SupportsSqlServer }).(pulumi.BoolOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) SupportsUefi() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.SupportsUefi }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Installation_TemplateResultOutput) TemplateName() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Installation_TemplateResult) string { return v.TemplateName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOvh_Me_Installation_TemplateResultOutput{})
}
