// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetOvh_Dbaas_Logs_Input_Engine(ctx *pulumi.Context, args *GetOvh_Dbaas_Logs_Input_EngineArgs, opts ...pulumi.InvokeOption) (*GetOvh_Dbaas_Logs_Input_EngineResult, error) {
	var rv GetOvh_Dbaas_Logs_Input_EngineResult
	err := ctx.Invoke("ovh:index/getOvh_Dbaas_Logs_Input_Engine:getOvh_Dbaas_Logs_Input_Engine", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOvh_Dbaas_Logs_Input_Engine.
type GetOvh_Dbaas_Logs_Input_EngineArgs struct {
	IsDeprecated *bool   `pulumi:"isDeprecated"`
	Name         *string `pulumi:"name"`
	Version      *string `pulumi:"version"`
}

// A collection of values returned by getOvh_Dbaas_Logs_Input_Engine.
type GetOvh_Dbaas_Logs_Input_EngineResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id           string `pulumi:"id"`
	IsDeprecated bool   `pulumi:"isDeprecated"`
	Name         string `pulumi:"name"`
	Version      string `pulumi:"version"`
}

func GetOvh_Dbaas_Logs_Input_EngineOutput(ctx *pulumi.Context, args GetOvh_Dbaas_Logs_Input_EngineOutputArgs, opts ...pulumi.InvokeOption) GetOvh_Dbaas_Logs_Input_EngineResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOvh_Dbaas_Logs_Input_EngineResult, error) {
			args := v.(GetOvh_Dbaas_Logs_Input_EngineArgs)
			r, err := GetOvh_Dbaas_Logs_Input_Engine(ctx, &args, opts...)
			return *r, err
		}).(GetOvh_Dbaas_Logs_Input_EngineResultOutput)
}

// A collection of arguments for invoking getOvh_Dbaas_Logs_Input_Engine.
type GetOvh_Dbaas_Logs_Input_EngineOutputArgs struct {
	IsDeprecated pulumi.BoolPtrInput   `pulumi:"isDeprecated"`
	Name         pulumi.StringPtrInput `pulumi:"name"`
	Version      pulumi.StringPtrInput `pulumi:"version"`
}

func (GetOvh_Dbaas_Logs_Input_EngineOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Dbaas_Logs_Input_EngineArgs)(nil)).Elem()
}

// A collection of values returned by getOvh_Dbaas_Logs_Input_Engine.
type GetOvh_Dbaas_Logs_Input_EngineResultOutput struct{ *pulumi.OutputState }

func (GetOvh_Dbaas_Logs_Input_EngineResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Dbaas_Logs_Input_EngineResult)(nil)).Elem()
}

func (o GetOvh_Dbaas_Logs_Input_EngineResultOutput) ToGetOvh_Dbaas_Logs_Input_EngineResultOutput() GetOvh_Dbaas_Logs_Input_EngineResultOutput {
	return o
}

func (o GetOvh_Dbaas_Logs_Input_EngineResultOutput) ToGetOvh_Dbaas_Logs_Input_EngineResultOutputWithContext(ctx context.Context) GetOvh_Dbaas_Logs_Input_EngineResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetOvh_Dbaas_Logs_Input_EngineResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Dbaas_Logs_Input_EngineResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetOvh_Dbaas_Logs_Input_EngineResultOutput) IsDeprecated() pulumi.BoolOutput {
	return o.ApplyT(func(v GetOvh_Dbaas_Logs_Input_EngineResult) bool { return v.IsDeprecated }).(pulumi.BoolOutput)
}

func (o GetOvh_Dbaas_Logs_Input_EngineResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Dbaas_Logs_Input_EngineResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetOvh_Dbaas_Logs_Input_EngineResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Dbaas_Logs_Input_EngineResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOvh_Dbaas_Logs_Input_EngineResultOutput{})
}
