// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetOvh_Order_Cart_Product_Options(ctx *pulumi.Context, args *GetOvh_Order_Cart_Product_OptionsArgs, opts ...pulumi.InvokeOption) (*GetOvh_Order_Cart_Product_OptionsResult, error) {
	var rv GetOvh_Order_Cart_Product_OptionsResult
	err := ctx.Invoke("ovh:index/getOvh_Order_Cart_Product_Options:getOvh_Order_Cart_Product_Options", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOvh_Order_Cart_Product_Options.
type GetOvh_Order_Cart_Product_OptionsArgs struct {
	CartId      string  `pulumi:"cartId"`
	CatalogName *string `pulumi:"catalogName"`
	PlanCode    string  `pulumi:"planCode"`
	Product     string  `pulumi:"product"`
}

// A collection of values returned by getOvh_Order_Cart_Product_Options.
type GetOvh_Order_Cart_Product_OptionsResult struct {
	CartId      string  `pulumi:"cartId"`
	CatalogName *string `pulumi:"catalogName"`
	// The provider-assigned unique ID for this managed resource.
	Id       string                                    `pulumi:"id"`
	PlanCode string                                    `pulumi:"planCode"`
	Product  string                                    `pulumi:"product"`
	Results  []GetOvh_Order_Cart_Product_OptionsResult `pulumi:"results"`
}

func GetOvh_Order_Cart_Product_OptionsOutput(ctx *pulumi.Context, args GetOvh_Order_Cart_Product_OptionsOutputArgs, opts ...pulumi.InvokeOption) GetOvh_Order_Cart_Product_OptionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOvh_Order_Cart_Product_OptionsResult, error) {
			args := v.(GetOvh_Order_Cart_Product_OptionsArgs)
			r, err := GetOvh_Order_Cart_Product_Options(ctx, &args, opts...)
			return *r, err
		}).(GetOvh_Order_Cart_Product_OptionsResultOutput)
}

// A collection of arguments for invoking getOvh_Order_Cart_Product_Options.
type GetOvh_Order_Cart_Product_OptionsOutputArgs struct {
	CartId      pulumi.StringInput    `pulumi:"cartId"`
	CatalogName pulumi.StringPtrInput `pulumi:"catalogName"`
	PlanCode    pulumi.StringInput    `pulumi:"planCode"`
	Product     pulumi.StringInput    `pulumi:"product"`
}

func (GetOvh_Order_Cart_Product_OptionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Order_Cart_Product_OptionsArgs)(nil)).Elem()
}

// A collection of values returned by getOvh_Order_Cart_Product_Options.
type GetOvh_Order_Cart_Product_OptionsResultOutput struct{ *pulumi.OutputState }

func (GetOvh_Order_Cart_Product_OptionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Order_Cart_Product_OptionsResult)(nil)).Elem()
}

func (o GetOvh_Order_Cart_Product_OptionsResultOutput) ToGetOvh_Order_Cart_Product_OptionsResultOutput() GetOvh_Order_Cart_Product_OptionsResultOutput {
	return o
}

func (o GetOvh_Order_Cart_Product_OptionsResultOutput) ToGetOvh_Order_Cart_Product_OptionsResultOutputWithContext(ctx context.Context) GetOvh_Order_Cart_Product_OptionsResultOutput {
	return o
}

func (o GetOvh_Order_Cart_Product_OptionsResultOutput) CartId() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Order_Cart_Product_OptionsResult) string { return v.CartId }).(pulumi.StringOutput)
}

func (o GetOvh_Order_Cart_Product_OptionsResultOutput) CatalogName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetOvh_Order_Cart_Product_OptionsResult) *string { return v.CatalogName }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetOvh_Order_Cart_Product_OptionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Order_Cart_Product_OptionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetOvh_Order_Cart_Product_OptionsResultOutput) PlanCode() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Order_Cart_Product_OptionsResult) string { return v.PlanCode }).(pulumi.StringOutput)
}

func (o GetOvh_Order_Cart_Product_OptionsResultOutput) Product() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Order_Cart_Product_OptionsResult) string { return v.Product }).(pulumi.StringOutput)
}

func (o GetOvh_Order_Cart_Product_OptionsResultOutput) Results() GetOvh_Order_Cart_Product_OptionsResultArrayOutput {
	return o.ApplyT(func(v GetOvh_Order_Cart_Product_OptionsResult) []GetOvh_Order_Cart_Product_OptionsResult {
		return v.Results
	}).(GetOvh_Order_Cart_Product_OptionsResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOvh_Order_Cart_Product_OptionsResultOutput{})
}
