// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetOvh_Cloud_Project_Regions(ctx *pulumi.Context, args *GetOvh_Cloud_Project_RegionsArgs, opts ...pulumi.InvokeOption) (*GetOvh_Cloud_Project_RegionsResult, error) {
	var rv GetOvh_Cloud_Project_RegionsResult
	err := ctx.Invoke("ovh:index/getOvh_Cloud_Project_Regions:getOvh_Cloud_Project_Regions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOvh_Cloud_Project_Regions.
type GetOvh_Cloud_Project_RegionsArgs struct {
	HasServicesUps []string `pulumi:"hasServicesUps"`
	ServiceName    string   `pulumi:"serviceName"`
}

// A collection of values returned by getOvh_Cloud_Project_Regions.
type GetOvh_Cloud_Project_RegionsResult struct {
	HasServicesUps []string `pulumi:"hasServicesUps"`
	// The provider-assigned unique ID for this managed resource.
	Id          string   `pulumi:"id"`
	Names       []string `pulumi:"names"`
	ServiceName string   `pulumi:"serviceName"`
}

func GetOvh_Cloud_Project_RegionsOutput(ctx *pulumi.Context, args GetOvh_Cloud_Project_RegionsOutputArgs, opts ...pulumi.InvokeOption) GetOvh_Cloud_Project_RegionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOvh_Cloud_Project_RegionsResult, error) {
			args := v.(GetOvh_Cloud_Project_RegionsArgs)
			r, err := GetOvh_Cloud_Project_Regions(ctx, &args, opts...)
			return *r, err
		}).(GetOvh_Cloud_Project_RegionsResultOutput)
}

// A collection of arguments for invoking getOvh_Cloud_Project_Regions.
type GetOvh_Cloud_Project_RegionsOutputArgs struct {
	HasServicesUps pulumi.StringArrayInput `pulumi:"hasServicesUps"`
	ServiceName    pulumi.StringInput      `pulumi:"serviceName"`
}

func (GetOvh_Cloud_Project_RegionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Cloud_Project_RegionsArgs)(nil)).Elem()
}

// A collection of values returned by getOvh_Cloud_Project_Regions.
type GetOvh_Cloud_Project_RegionsResultOutput struct{ *pulumi.OutputState }

func (GetOvh_Cloud_Project_RegionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Cloud_Project_RegionsResult)(nil)).Elem()
}

func (o GetOvh_Cloud_Project_RegionsResultOutput) ToGetOvh_Cloud_Project_RegionsResultOutput() GetOvh_Cloud_Project_RegionsResultOutput {
	return o
}

func (o GetOvh_Cloud_Project_RegionsResultOutput) ToGetOvh_Cloud_Project_RegionsResultOutputWithContext(ctx context.Context) GetOvh_Cloud_Project_RegionsResultOutput {
	return o
}

func (o GetOvh_Cloud_Project_RegionsResultOutput) HasServicesUps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOvh_Cloud_Project_RegionsResult) []string { return v.HasServicesUps }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetOvh_Cloud_Project_RegionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Cloud_Project_RegionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetOvh_Cloud_Project_RegionsResultOutput) Names() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOvh_Cloud_Project_RegionsResult) []string { return v.Names }).(pulumi.StringArrayOutput)
}

func (o GetOvh_Cloud_Project_RegionsResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Cloud_Project_RegionsResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOvh_Cloud_Project_RegionsResultOutput{})
}
