// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetOvh_Me_Ipxe_Script(ctx *pulumi.Context, args *GetOvh_Me_Ipxe_ScriptArgs, opts ...pulumi.InvokeOption) (*GetOvh_Me_Ipxe_ScriptResult, error) {
	var rv GetOvh_Me_Ipxe_ScriptResult
	err := ctx.Invoke("ovh:index/getOvh_Me_Ipxe_Script:getOvh_Me_Ipxe_Script", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOvh_Me_Ipxe_Script.
type GetOvh_Me_Ipxe_ScriptArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getOvh_Me_Ipxe_Script.
type GetOvh_Me_Ipxe_ScriptResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id     string `pulumi:"id"`
	Name   string `pulumi:"name"`
	Script string `pulumi:"script"`
}

func GetOvh_Me_Ipxe_ScriptOutput(ctx *pulumi.Context, args GetOvh_Me_Ipxe_ScriptOutputArgs, opts ...pulumi.InvokeOption) GetOvh_Me_Ipxe_ScriptResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOvh_Me_Ipxe_ScriptResult, error) {
			args := v.(GetOvh_Me_Ipxe_ScriptArgs)
			r, err := GetOvh_Me_Ipxe_Script(ctx, &args, opts...)
			return *r, err
		}).(GetOvh_Me_Ipxe_ScriptResultOutput)
}

// A collection of arguments for invoking getOvh_Me_Ipxe_Script.
type GetOvh_Me_Ipxe_ScriptOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetOvh_Me_Ipxe_ScriptOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Me_Ipxe_ScriptArgs)(nil)).Elem()
}

// A collection of values returned by getOvh_Me_Ipxe_Script.
type GetOvh_Me_Ipxe_ScriptResultOutput struct{ *pulumi.OutputState }

func (GetOvh_Me_Ipxe_ScriptResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Me_Ipxe_ScriptResult)(nil)).Elem()
}

func (o GetOvh_Me_Ipxe_ScriptResultOutput) ToGetOvh_Me_Ipxe_ScriptResultOutput() GetOvh_Me_Ipxe_ScriptResultOutput {
	return o
}

func (o GetOvh_Me_Ipxe_ScriptResultOutput) ToGetOvh_Me_Ipxe_ScriptResultOutputWithContext(ctx context.Context) GetOvh_Me_Ipxe_ScriptResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetOvh_Me_Ipxe_ScriptResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Ipxe_ScriptResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Ipxe_ScriptResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Ipxe_ScriptResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Ipxe_ScriptResultOutput) Script() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Ipxe_ScriptResult) string { return v.Script }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOvh_Me_Ipxe_ScriptResultOutput{})
}
