// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetOvh_Me_Identity_User(ctx *pulumi.Context, args *GetOvh_Me_Identity_UserArgs, opts ...pulumi.InvokeOption) (*GetOvh_Me_Identity_UserResult, error) {
	var rv GetOvh_Me_Identity_UserResult
	err := ctx.Invoke("ovh:index/getOvh_Me_Identity_User:getOvh_Me_Identity_User", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOvh_Me_Identity_User.
type GetOvh_Me_Identity_UserArgs struct {
	User string `pulumi:"user"`
}

// A collection of values returned by getOvh_Me_Identity_User.
type GetOvh_Me_Identity_UserResult struct {
	Creation    string `pulumi:"creation"`
	Description string `pulumi:"description"`
	Email       string `pulumi:"email"`
	Group       string `pulumi:"group"`
	// The provider-assigned unique ID for this managed resource.
	Id                 string `pulumi:"id"`
	LastUpdate         string `pulumi:"lastUpdate"`
	Login              string `pulumi:"login"`
	PasswordLastUpdate string `pulumi:"passwordLastUpdate"`
	Status             string `pulumi:"status"`
	User               string `pulumi:"user"`
}

func GetOvh_Me_Identity_UserOutput(ctx *pulumi.Context, args GetOvh_Me_Identity_UserOutputArgs, opts ...pulumi.InvokeOption) GetOvh_Me_Identity_UserResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOvh_Me_Identity_UserResult, error) {
			args := v.(GetOvh_Me_Identity_UserArgs)
			r, err := GetOvh_Me_Identity_User(ctx, &args, opts...)
			return *r, err
		}).(GetOvh_Me_Identity_UserResultOutput)
}

// A collection of arguments for invoking getOvh_Me_Identity_User.
type GetOvh_Me_Identity_UserOutputArgs struct {
	User pulumi.StringInput `pulumi:"user"`
}

func (GetOvh_Me_Identity_UserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Me_Identity_UserArgs)(nil)).Elem()
}

// A collection of values returned by getOvh_Me_Identity_User.
type GetOvh_Me_Identity_UserResultOutput struct{ *pulumi.OutputState }

func (GetOvh_Me_Identity_UserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOvh_Me_Identity_UserResult)(nil)).Elem()
}

func (o GetOvh_Me_Identity_UserResultOutput) ToGetOvh_Me_Identity_UserResultOutput() GetOvh_Me_Identity_UserResultOutput {
	return o
}

func (o GetOvh_Me_Identity_UserResultOutput) ToGetOvh_Me_Identity_UserResultOutputWithContext(ctx context.Context) GetOvh_Me_Identity_UserResultOutput {
	return o
}

func (o GetOvh_Me_Identity_UserResultOutput) Creation() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.Creation }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Identity_UserResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Identity_UserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.Email }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Identity_UserResultOutput) Group() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.Group }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetOvh_Me_Identity_UserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Identity_UserResultOutput) LastUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.LastUpdate }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Identity_UserResultOutput) Login() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.Login }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Identity_UserResultOutput) PasswordLastUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.PasswordLastUpdate }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Identity_UserResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetOvh_Me_Identity_UserResultOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v GetOvh_Me_Identity_UserResult) string { return v.User }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOvh_Me_Identity_UserResultOutput{})
}
