// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetOvh_Me_Ipxe_Scripts(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetOvh_Me_Ipxe_ScriptsResult, error) {
	var rv GetOvh_Me_Ipxe_ScriptsResult
	err := ctx.Invoke("ovh:index/getOvh_Me_Ipxe_Scripts:getOvh_Me_Ipxe_Scripts", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getOvh_Me_Ipxe_Scripts.
type GetOvh_Me_Ipxe_ScriptsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id      string   `pulumi:"id"`
	Results []string `pulumi:"results"`
}
