// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetVps(ctx *pulumi.Context, args *GetVpsArgs, opts ...pulumi.InvokeOption) (*GetVpsResult, error) {
	var rv GetVpsResult
	err := ctx.Invoke("ovh:index/getVps:getVps", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVps.
type GetVpsArgs struct {
	ServiceName string `pulumi:"serviceName"`
}

// A collection of values returned by getVps.
type GetVpsResult struct {
	Cluster     string            `pulumi:"cluster"`
	Datacenter  map[string]string `pulumi:"datacenter"`
	Displayname string            `pulumi:"displayname"`
	// The provider-assigned unique ID for this managed resource.
	Id            string            `pulumi:"id"`
	Ips           []string          `pulumi:"ips"`
	Keymap        string            `pulumi:"keymap"`
	Memory        int               `pulumi:"memory"`
	Model         map[string]string `pulumi:"model"`
	Name          string            `pulumi:"name"`
	Netbootmode   string            `pulumi:"netbootmode"`
	Offertype     string            `pulumi:"offertype"`
	ServiceName   string            `pulumi:"serviceName"`
	Slamonitoring bool              `pulumi:"slamonitoring"`
	State         string            `pulumi:"state"`
	Type          string            `pulumi:"type"`
	Vcore         int               `pulumi:"vcore"`
	Zone          string            `pulumi:"zone"`
}

func GetVpsOutput(ctx *pulumi.Context, args GetVpsOutputArgs, opts ...pulumi.InvokeOption) GetVpsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVpsResult, error) {
			args := v.(GetVpsArgs)
			r, err := GetVps(ctx, &args, opts...)
			return *r, err
		}).(GetVpsResultOutput)
}

// A collection of arguments for invoking getVps.
type GetVpsOutputArgs struct {
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
}

func (GetVpsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpsArgs)(nil)).Elem()
}

// A collection of values returned by getVps.
type GetVpsResultOutput struct{ *pulumi.OutputState }

func (GetVpsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpsResult)(nil)).Elem()
}

func (o GetVpsResultOutput) ToGetVpsResultOutput() GetVpsResultOutput {
	return o
}

func (o GetVpsResultOutput) ToGetVpsResultOutputWithContext(ctx context.Context) GetVpsResultOutput {
	return o
}

func (o GetVpsResultOutput) Cluster() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Cluster }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) Datacenter() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetVpsResult) map[string]string { return v.Datacenter }).(pulumi.StringMapOutput)
}

func (o GetVpsResultOutput) Displayname() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Displayname }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetVpsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetVpsResult) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

func (o GetVpsResultOutput) Keymap() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Keymap }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) Memory() pulumi.IntOutput {
	return o.ApplyT(func(v GetVpsResult) int { return v.Memory }).(pulumi.IntOutput)
}

func (o GetVpsResultOutput) Model() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetVpsResult) map[string]string { return v.Model }).(pulumi.StringMapOutput)
}

func (o GetVpsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) Netbootmode() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Netbootmode }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) Offertype() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Offertype }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) Slamonitoring() pulumi.BoolOutput {
	return o.ApplyT(func(v GetVpsResult) bool { return v.Slamonitoring }).(pulumi.BoolOutput)
}

func (o GetVpsResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.State }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o GetVpsResultOutput) Vcore() pulumi.IntOutput {
	return o.ApplyT(func(v GetVpsResult) int { return v.Vcore }).(pulumi.IntOutput)
}

func (o GetVpsResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpsResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVpsResultOutput{})
}
