// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Ovh_cloud_project struct {
	pulumi.CustomResourceState

	Access      pulumi.StringOutput `pulumi:"access"`
	Description pulumi.StringOutput `pulumi:"description"`
	// Details about an Order
	Orders Ovh_cloud_projectOrderArrayOutput `pulumi:"orders"`
	// Ovh Subsidiary
	OvhSubsidiary pulumi.StringOutput `pulumi:"ovhSubsidiary"`
	// Ovh payment mode
	PaymentMean pulumi.StringOutput `pulumi:"paymentMean"`
	// Product Plan to order
	Plan Ovh_cloud_projectPlanOutput `pulumi:"plan"`
	// Product Plan to order
	PlanOptions Ovh_cloud_projectPlanOptionArrayOutput `pulumi:"planOptions"`
	ProjectId   pulumi.StringOutput                    `pulumi:"projectId"`
	ProjectName pulumi.StringOutput                    `pulumi:"projectName"`
	Status      pulumi.StringOutput                    `pulumi:"status"`
}

// NewOvh_cloud_project registers a new resource with the given unique name, arguments, and options.
func NewOvh_cloud_project(ctx *pulumi.Context,
	name string, args *Ovh_cloud_projectArgs, opts ...pulumi.ResourceOption) (*Ovh_cloud_project, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OvhSubsidiary == nil {
		return nil, errors.New("invalid value for required argument 'OvhSubsidiary'")
	}
	if args.PaymentMean == nil {
		return nil, errors.New("invalid value for required argument 'PaymentMean'")
	}
	if args.Plan == nil {
		return nil, errors.New("invalid value for required argument 'Plan'")
	}
	var resource Ovh_cloud_project
	err := ctx.RegisterResource("ovh:index/ovh_cloud_project:ovh_cloud_project", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOvh_cloud_project gets an existing Ovh_cloud_project resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOvh_cloud_project(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *Ovh_cloud_projectState, opts ...pulumi.ResourceOption) (*Ovh_cloud_project, error) {
	var resource Ovh_cloud_project
	err := ctx.ReadResource("ovh:index/ovh_cloud_project:ovh_cloud_project", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Ovh_cloud_project resources.
type ovh_cloud_projectState struct {
	Access      *string `pulumi:"access"`
	Description *string `pulumi:"description"`
	// Details about an Order
	Orders []Ovh_cloud_projectOrder `pulumi:"orders"`
	// Ovh Subsidiary
	OvhSubsidiary *string `pulumi:"ovhSubsidiary"`
	// Ovh payment mode
	PaymentMean *string `pulumi:"paymentMean"`
	// Product Plan to order
	Plan *Ovh_cloud_projectPlan `pulumi:"plan"`
	// Product Plan to order
	PlanOptions []Ovh_cloud_projectPlanOption `pulumi:"planOptions"`
	ProjectId   *string                       `pulumi:"projectId"`
	ProjectName *string                       `pulumi:"projectName"`
	Status      *string                       `pulumi:"status"`
}

type Ovh_cloud_projectState struct {
	Access      pulumi.StringPtrInput
	Description pulumi.StringPtrInput
	// Details about an Order
	Orders Ovh_cloud_projectOrderArrayInput
	// Ovh Subsidiary
	OvhSubsidiary pulumi.StringPtrInput
	// Ovh payment mode
	PaymentMean pulumi.StringPtrInput
	// Product Plan to order
	Plan Ovh_cloud_projectPlanPtrInput
	// Product Plan to order
	PlanOptions Ovh_cloud_projectPlanOptionArrayInput
	ProjectId   pulumi.StringPtrInput
	ProjectName pulumi.StringPtrInput
	Status      pulumi.StringPtrInput
}

func (Ovh_cloud_projectState) ElementType() reflect.Type {
	return reflect.TypeOf((*ovh_cloud_projectState)(nil)).Elem()
}

type ovh_cloud_projectArgs struct {
	Description *string `pulumi:"description"`
	// Ovh Subsidiary
	OvhSubsidiary string `pulumi:"ovhSubsidiary"`
	// Ovh payment mode
	PaymentMean string `pulumi:"paymentMean"`
	// Product Plan to order
	Plan Ovh_cloud_projectPlan `pulumi:"plan"`
	// Product Plan to order
	PlanOptions []Ovh_cloud_projectPlanOption `pulumi:"planOptions"`
}

// The set of arguments for constructing a Ovh_cloud_project resource.
type Ovh_cloud_projectArgs struct {
	Description pulumi.StringPtrInput
	// Ovh Subsidiary
	OvhSubsidiary pulumi.StringInput
	// Ovh payment mode
	PaymentMean pulumi.StringInput
	// Product Plan to order
	Plan Ovh_cloud_projectPlanInput
	// Product Plan to order
	PlanOptions Ovh_cloud_projectPlanOptionArrayInput
}

func (Ovh_cloud_projectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ovh_cloud_projectArgs)(nil)).Elem()
}

type Ovh_cloud_projectInput interface {
	pulumi.Input

	ToOvh_cloud_projectOutput() Ovh_cloud_projectOutput
	ToOvh_cloud_projectOutputWithContext(ctx context.Context) Ovh_cloud_projectOutput
}

func (*Ovh_cloud_project) ElementType() reflect.Type {
	return reflect.TypeOf((*Ovh_cloud_project)(nil))
}

func (i *Ovh_cloud_project) ToOvh_cloud_projectOutput() Ovh_cloud_projectOutput {
	return i.ToOvh_cloud_projectOutputWithContext(context.Background())
}

func (i *Ovh_cloud_project) ToOvh_cloud_projectOutputWithContext(ctx context.Context) Ovh_cloud_projectOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_projectOutput)
}

func (i *Ovh_cloud_project) ToOvh_cloud_projectPtrOutput() Ovh_cloud_projectPtrOutput {
	return i.ToOvh_cloud_projectPtrOutputWithContext(context.Background())
}

func (i *Ovh_cloud_project) ToOvh_cloud_projectPtrOutputWithContext(ctx context.Context) Ovh_cloud_projectPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_projectPtrOutput)
}

type Ovh_cloud_projectPtrInput interface {
	pulumi.Input

	ToOvh_cloud_projectPtrOutput() Ovh_cloud_projectPtrOutput
	ToOvh_cloud_projectPtrOutputWithContext(ctx context.Context) Ovh_cloud_projectPtrOutput
}

type ovh_cloud_projectPtrType Ovh_cloud_projectArgs

func (*ovh_cloud_projectPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Ovh_cloud_project)(nil))
}

func (i *ovh_cloud_projectPtrType) ToOvh_cloud_projectPtrOutput() Ovh_cloud_projectPtrOutput {
	return i.ToOvh_cloud_projectPtrOutputWithContext(context.Background())
}

func (i *ovh_cloud_projectPtrType) ToOvh_cloud_projectPtrOutputWithContext(ctx context.Context) Ovh_cloud_projectPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_projectPtrOutput)
}

// Ovh_cloud_projectArrayInput is an input type that accepts Ovh_cloud_projectArray and Ovh_cloud_projectArrayOutput values.
// You can construct a concrete instance of `Ovh_cloud_projectArrayInput` via:
//
//          Ovh_cloud_projectArray{ Ovh_cloud_projectArgs{...} }
type Ovh_cloud_projectArrayInput interface {
	pulumi.Input

	ToOvh_cloud_projectArrayOutput() Ovh_cloud_projectArrayOutput
	ToOvh_cloud_projectArrayOutputWithContext(context.Context) Ovh_cloud_projectArrayOutput
}

type Ovh_cloud_projectArray []Ovh_cloud_projectInput

func (Ovh_cloud_projectArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Ovh_cloud_project)(nil)).Elem()
}

func (i Ovh_cloud_projectArray) ToOvh_cloud_projectArrayOutput() Ovh_cloud_projectArrayOutput {
	return i.ToOvh_cloud_projectArrayOutputWithContext(context.Background())
}

func (i Ovh_cloud_projectArray) ToOvh_cloud_projectArrayOutputWithContext(ctx context.Context) Ovh_cloud_projectArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_projectArrayOutput)
}

// Ovh_cloud_projectMapInput is an input type that accepts Ovh_cloud_projectMap and Ovh_cloud_projectMapOutput values.
// You can construct a concrete instance of `Ovh_cloud_projectMapInput` via:
//
//          Ovh_cloud_projectMap{ "key": Ovh_cloud_projectArgs{...} }
type Ovh_cloud_projectMapInput interface {
	pulumi.Input

	ToOvh_cloud_projectMapOutput() Ovh_cloud_projectMapOutput
	ToOvh_cloud_projectMapOutputWithContext(context.Context) Ovh_cloud_projectMapOutput
}

type Ovh_cloud_projectMap map[string]Ovh_cloud_projectInput

func (Ovh_cloud_projectMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Ovh_cloud_project)(nil)).Elem()
}

func (i Ovh_cloud_projectMap) ToOvh_cloud_projectMapOutput() Ovh_cloud_projectMapOutput {
	return i.ToOvh_cloud_projectMapOutputWithContext(context.Background())
}

func (i Ovh_cloud_projectMap) ToOvh_cloud_projectMapOutputWithContext(ctx context.Context) Ovh_cloud_projectMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_projectMapOutput)
}

type Ovh_cloud_projectOutput struct{ *pulumi.OutputState }

func (Ovh_cloud_projectOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Ovh_cloud_project)(nil))
}

func (o Ovh_cloud_projectOutput) ToOvh_cloud_projectOutput() Ovh_cloud_projectOutput {
	return o
}

func (o Ovh_cloud_projectOutput) ToOvh_cloud_projectOutputWithContext(ctx context.Context) Ovh_cloud_projectOutput {
	return o
}

func (o Ovh_cloud_projectOutput) ToOvh_cloud_projectPtrOutput() Ovh_cloud_projectPtrOutput {
	return o.ToOvh_cloud_projectPtrOutputWithContext(context.Background())
}

func (o Ovh_cloud_projectOutput) ToOvh_cloud_projectPtrOutputWithContext(ctx context.Context) Ovh_cloud_projectPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Ovh_cloud_project) *Ovh_cloud_project {
		return &v
	}).(Ovh_cloud_projectPtrOutput)
}

type Ovh_cloud_projectPtrOutput struct{ *pulumi.OutputState }

func (Ovh_cloud_projectPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Ovh_cloud_project)(nil))
}

func (o Ovh_cloud_projectPtrOutput) ToOvh_cloud_projectPtrOutput() Ovh_cloud_projectPtrOutput {
	return o
}

func (o Ovh_cloud_projectPtrOutput) ToOvh_cloud_projectPtrOutputWithContext(ctx context.Context) Ovh_cloud_projectPtrOutput {
	return o
}

func (o Ovh_cloud_projectPtrOutput) Elem() Ovh_cloud_projectOutput {
	return o.ApplyT(func(v *Ovh_cloud_project) Ovh_cloud_project {
		if v != nil {
			return *v
		}
		var ret Ovh_cloud_project
		return ret
	}).(Ovh_cloud_projectOutput)
}

type Ovh_cloud_projectArrayOutput struct{ *pulumi.OutputState }

func (Ovh_cloud_projectArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Ovh_cloud_project)(nil))
}

func (o Ovh_cloud_projectArrayOutput) ToOvh_cloud_projectArrayOutput() Ovh_cloud_projectArrayOutput {
	return o
}

func (o Ovh_cloud_projectArrayOutput) ToOvh_cloud_projectArrayOutputWithContext(ctx context.Context) Ovh_cloud_projectArrayOutput {
	return o
}

func (o Ovh_cloud_projectArrayOutput) Index(i pulumi.IntInput) Ovh_cloud_projectOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Ovh_cloud_project {
		return vs[0].([]Ovh_cloud_project)[vs[1].(int)]
	}).(Ovh_cloud_projectOutput)
}

type Ovh_cloud_projectMapOutput struct{ *pulumi.OutputState }

func (Ovh_cloud_projectMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]Ovh_cloud_project)(nil))
}

func (o Ovh_cloud_projectMapOutput) ToOvh_cloud_projectMapOutput() Ovh_cloud_projectMapOutput {
	return o
}

func (o Ovh_cloud_projectMapOutput) ToOvh_cloud_projectMapOutputWithContext(ctx context.Context) Ovh_cloud_projectMapOutput {
	return o
}

func (o Ovh_cloud_projectMapOutput) MapIndex(k pulumi.StringInput) Ovh_cloud_projectOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) Ovh_cloud_project {
		return vs[0].(map[string]Ovh_cloud_project)[vs[1].(string)]
	}).(Ovh_cloud_projectOutput)
}

func init() {
	pulumi.RegisterOutputType(Ovh_cloud_projectOutput{})
	pulumi.RegisterOutputType(Ovh_cloud_projectPtrOutput{})
	pulumi.RegisterOutputType(Ovh_cloud_projectArrayOutput{})
	pulumi.RegisterOutputType(Ovh_cloud_projectMapOutput{})
}
