// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Ovh_iploadbalancing struct {
	pulumi.CustomResourceState

	// Set the name displayed in ManagerV6 for your iplb (max 50 chars)
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// Your IP load balancing
	IpLoadbalancing pulumi.StringOutput `pulumi:"ipLoadbalancing"`
	// The IPV4 associated to your IP load balancing
	Ipv4 pulumi.StringOutput `pulumi:"ipv4"`
	// The IPV6 associated to your IP load balancing. DEPRECATED.
	Ipv6 pulumi.StringOutput `pulumi:"ipv6"`
	// The metrics token associated with your IP load balancing
	MetricsToken pulumi.StringOutput `pulumi:"metricsToken"`
	// The offer of your IP load balancing
	Offer pulumi.StringOutput `pulumi:"offer"`
	// Available additional zone for your Load Balancer
	OrderableZones Ovh_iploadbalancingOrderableZoneArrayOutput `pulumi:"orderableZones"`
	// Details about an Order
	Orders Ovh_iploadbalancingOrderArrayOutput `pulumi:"orders"`
	// Ovh Subsidiary
	OvhSubsidiary pulumi.StringOutput `pulumi:"ovhSubsidiary"`
	// Ovh payment mode
	PaymentMean pulumi.StringOutput `pulumi:"paymentMean"`
	// Product Plan to order
	Plan Ovh_iploadbalancingPlanOutput `pulumi:"plan"`
	// Product Plan to order
	PlanOptions Ovh_iploadbalancingPlanOptionArrayOutput `pulumi:"planOptions"`
	// The internal name of your IP load balancing
	ServiceName pulumi.StringOutput `pulumi:"serviceName"`
	// Modern oldest compatible clients : Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, and
	// Java 8. Intermediate oldest compatible clients : Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android
	// 2.3, Java 7. Intermediate if null.
	SslConfiguration pulumi.StringOutput `pulumi:"sslConfiguration"`
	// Current state of your IP
	State pulumi.StringOutput `pulumi:"state"`
	// Vrack eligibility
	VrackEligibility pulumi.BoolOutput `pulumi:"vrackEligibility"`
	// Name of the vRack on which the current Load Balancer is attached to, as it is named on vRack product
	VrackName pulumi.StringOutput `pulumi:"vrackName"`
	// Location where your service is
	Zones pulumi.StringArrayOutput `pulumi:"zones"`
}

// NewOvh_iploadbalancing registers a new resource with the given unique name, arguments, and options.
func NewOvh_iploadbalancing(ctx *pulumi.Context,
	name string, args *Ovh_iploadbalancingArgs, opts ...pulumi.ResourceOption) (*Ovh_iploadbalancing, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OvhSubsidiary == nil {
		return nil, errors.New("invalid value for required argument 'OvhSubsidiary'")
	}
	if args.PaymentMean == nil {
		return nil, errors.New("invalid value for required argument 'PaymentMean'")
	}
	if args.Plan == nil {
		return nil, errors.New("invalid value for required argument 'Plan'")
	}
	var resource Ovh_iploadbalancing
	err := ctx.RegisterResource("ovh:index/ovh_iploadbalancing:ovh_iploadbalancing", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOvh_iploadbalancing gets an existing Ovh_iploadbalancing resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOvh_iploadbalancing(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *Ovh_iploadbalancingState, opts ...pulumi.ResourceOption) (*Ovh_iploadbalancing, error) {
	var resource Ovh_iploadbalancing
	err := ctx.ReadResource("ovh:index/ovh_iploadbalancing:ovh_iploadbalancing", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Ovh_iploadbalancing resources.
type ovh_iploadbalancingState struct {
	// Set the name displayed in ManagerV6 for your iplb (max 50 chars)
	DisplayName *string `pulumi:"displayName"`
	// Your IP load balancing
	IpLoadbalancing *string `pulumi:"ipLoadbalancing"`
	// The IPV4 associated to your IP load balancing
	Ipv4 *string `pulumi:"ipv4"`
	// The IPV6 associated to your IP load balancing. DEPRECATED.
	Ipv6 *string `pulumi:"ipv6"`
	// The metrics token associated with your IP load balancing
	MetricsToken *string `pulumi:"metricsToken"`
	// The offer of your IP load balancing
	Offer *string `pulumi:"offer"`
	// Available additional zone for your Load Balancer
	OrderableZones []Ovh_iploadbalancingOrderableZone `pulumi:"orderableZones"`
	// Details about an Order
	Orders []Ovh_iploadbalancingOrder `pulumi:"orders"`
	// Ovh Subsidiary
	OvhSubsidiary *string `pulumi:"ovhSubsidiary"`
	// Ovh payment mode
	PaymentMean *string `pulumi:"paymentMean"`
	// Product Plan to order
	Plan *Ovh_iploadbalancingPlan `pulumi:"plan"`
	// Product Plan to order
	PlanOptions []Ovh_iploadbalancingPlanOption `pulumi:"planOptions"`
	// The internal name of your IP load balancing
	ServiceName *string `pulumi:"serviceName"`
	// Modern oldest compatible clients : Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, and
	// Java 8. Intermediate oldest compatible clients : Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android
	// 2.3, Java 7. Intermediate if null.
	SslConfiguration *string `pulumi:"sslConfiguration"`
	// Current state of your IP
	State *string `pulumi:"state"`
	// Vrack eligibility
	VrackEligibility *bool `pulumi:"vrackEligibility"`
	// Name of the vRack on which the current Load Balancer is attached to, as it is named on vRack product
	VrackName *string `pulumi:"vrackName"`
	// Location where your service is
	Zones []string `pulumi:"zones"`
}

type Ovh_iploadbalancingState struct {
	// Set the name displayed in ManagerV6 for your iplb (max 50 chars)
	DisplayName pulumi.StringPtrInput
	// Your IP load balancing
	IpLoadbalancing pulumi.StringPtrInput
	// The IPV4 associated to your IP load balancing
	Ipv4 pulumi.StringPtrInput
	// The IPV6 associated to your IP load balancing. DEPRECATED.
	Ipv6 pulumi.StringPtrInput
	// The metrics token associated with your IP load balancing
	MetricsToken pulumi.StringPtrInput
	// The offer of your IP load balancing
	Offer pulumi.StringPtrInput
	// Available additional zone for your Load Balancer
	OrderableZones Ovh_iploadbalancingOrderableZoneArrayInput
	// Details about an Order
	Orders Ovh_iploadbalancingOrderArrayInput
	// Ovh Subsidiary
	OvhSubsidiary pulumi.StringPtrInput
	// Ovh payment mode
	PaymentMean pulumi.StringPtrInput
	// Product Plan to order
	Plan Ovh_iploadbalancingPlanPtrInput
	// Product Plan to order
	PlanOptions Ovh_iploadbalancingPlanOptionArrayInput
	// The internal name of your IP load balancing
	ServiceName pulumi.StringPtrInput
	// Modern oldest compatible clients : Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, and
	// Java 8. Intermediate oldest compatible clients : Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android
	// 2.3, Java 7. Intermediate if null.
	SslConfiguration pulumi.StringPtrInput
	// Current state of your IP
	State pulumi.StringPtrInput
	// Vrack eligibility
	VrackEligibility pulumi.BoolPtrInput
	// Name of the vRack on which the current Load Balancer is attached to, as it is named on vRack product
	VrackName pulumi.StringPtrInput
	// Location where your service is
	Zones pulumi.StringArrayInput
}

func (Ovh_iploadbalancingState) ElementType() reflect.Type {
	return reflect.TypeOf((*ovh_iploadbalancingState)(nil)).Elem()
}

type ovh_iploadbalancingArgs struct {
	// Set the name displayed in ManagerV6 for your iplb (max 50 chars)
	DisplayName *string `pulumi:"displayName"`
	// Ovh Subsidiary
	OvhSubsidiary string `pulumi:"ovhSubsidiary"`
	// Ovh payment mode
	PaymentMean string `pulumi:"paymentMean"`
	// Product Plan to order
	Plan Ovh_iploadbalancingPlan `pulumi:"plan"`
	// Product Plan to order
	PlanOptions []Ovh_iploadbalancingPlanOption `pulumi:"planOptions"`
	// Modern oldest compatible clients : Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, and
	// Java 8. Intermediate oldest compatible clients : Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android
	// 2.3, Java 7. Intermediate if null.
	SslConfiguration *string `pulumi:"sslConfiguration"`
}

// The set of arguments for constructing a Ovh_iploadbalancing resource.
type Ovh_iploadbalancingArgs struct {
	// Set the name displayed in ManagerV6 for your iplb (max 50 chars)
	DisplayName pulumi.StringPtrInput
	// Ovh Subsidiary
	OvhSubsidiary pulumi.StringInput
	// Ovh payment mode
	PaymentMean pulumi.StringInput
	// Product Plan to order
	Plan Ovh_iploadbalancingPlanInput
	// Product Plan to order
	PlanOptions Ovh_iploadbalancingPlanOptionArrayInput
	// Modern oldest compatible clients : Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, and
	// Java 8. Intermediate oldest compatible clients : Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android
	// 2.3, Java 7. Intermediate if null.
	SslConfiguration pulumi.StringPtrInput
}

func (Ovh_iploadbalancingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ovh_iploadbalancingArgs)(nil)).Elem()
}

type Ovh_iploadbalancingInput interface {
	pulumi.Input

	ToOvh_iploadbalancingOutput() Ovh_iploadbalancingOutput
	ToOvh_iploadbalancingOutputWithContext(ctx context.Context) Ovh_iploadbalancingOutput
}

func (*Ovh_iploadbalancing) ElementType() reflect.Type {
	return reflect.TypeOf((*Ovh_iploadbalancing)(nil))
}

func (i *Ovh_iploadbalancing) ToOvh_iploadbalancingOutput() Ovh_iploadbalancingOutput {
	return i.ToOvh_iploadbalancingOutputWithContext(context.Background())
}

func (i *Ovh_iploadbalancing) ToOvh_iploadbalancingOutputWithContext(ctx context.Context) Ovh_iploadbalancingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_iploadbalancingOutput)
}

func (i *Ovh_iploadbalancing) ToOvh_iploadbalancingPtrOutput() Ovh_iploadbalancingPtrOutput {
	return i.ToOvh_iploadbalancingPtrOutputWithContext(context.Background())
}

func (i *Ovh_iploadbalancing) ToOvh_iploadbalancingPtrOutputWithContext(ctx context.Context) Ovh_iploadbalancingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_iploadbalancingPtrOutput)
}

type Ovh_iploadbalancingPtrInput interface {
	pulumi.Input

	ToOvh_iploadbalancingPtrOutput() Ovh_iploadbalancingPtrOutput
	ToOvh_iploadbalancingPtrOutputWithContext(ctx context.Context) Ovh_iploadbalancingPtrOutput
}

type ovh_iploadbalancingPtrType Ovh_iploadbalancingArgs

func (*ovh_iploadbalancingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Ovh_iploadbalancing)(nil))
}

func (i *ovh_iploadbalancingPtrType) ToOvh_iploadbalancingPtrOutput() Ovh_iploadbalancingPtrOutput {
	return i.ToOvh_iploadbalancingPtrOutputWithContext(context.Background())
}

func (i *ovh_iploadbalancingPtrType) ToOvh_iploadbalancingPtrOutputWithContext(ctx context.Context) Ovh_iploadbalancingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_iploadbalancingPtrOutput)
}

// Ovh_iploadbalancingArrayInput is an input type that accepts Ovh_iploadbalancingArray and Ovh_iploadbalancingArrayOutput values.
// You can construct a concrete instance of `Ovh_iploadbalancingArrayInput` via:
//
//          Ovh_iploadbalancingArray{ Ovh_iploadbalancingArgs{...} }
type Ovh_iploadbalancingArrayInput interface {
	pulumi.Input

	ToOvh_iploadbalancingArrayOutput() Ovh_iploadbalancingArrayOutput
	ToOvh_iploadbalancingArrayOutputWithContext(context.Context) Ovh_iploadbalancingArrayOutput
}

type Ovh_iploadbalancingArray []Ovh_iploadbalancingInput

func (Ovh_iploadbalancingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Ovh_iploadbalancing)(nil)).Elem()
}

func (i Ovh_iploadbalancingArray) ToOvh_iploadbalancingArrayOutput() Ovh_iploadbalancingArrayOutput {
	return i.ToOvh_iploadbalancingArrayOutputWithContext(context.Background())
}

func (i Ovh_iploadbalancingArray) ToOvh_iploadbalancingArrayOutputWithContext(ctx context.Context) Ovh_iploadbalancingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_iploadbalancingArrayOutput)
}

// Ovh_iploadbalancingMapInput is an input type that accepts Ovh_iploadbalancingMap and Ovh_iploadbalancingMapOutput values.
// You can construct a concrete instance of `Ovh_iploadbalancingMapInput` via:
//
//          Ovh_iploadbalancingMap{ "key": Ovh_iploadbalancingArgs{...} }
type Ovh_iploadbalancingMapInput interface {
	pulumi.Input

	ToOvh_iploadbalancingMapOutput() Ovh_iploadbalancingMapOutput
	ToOvh_iploadbalancingMapOutputWithContext(context.Context) Ovh_iploadbalancingMapOutput
}

type Ovh_iploadbalancingMap map[string]Ovh_iploadbalancingInput

func (Ovh_iploadbalancingMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Ovh_iploadbalancing)(nil)).Elem()
}

func (i Ovh_iploadbalancingMap) ToOvh_iploadbalancingMapOutput() Ovh_iploadbalancingMapOutput {
	return i.ToOvh_iploadbalancingMapOutputWithContext(context.Background())
}

func (i Ovh_iploadbalancingMap) ToOvh_iploadbalancingMapOutputWithContext(ctx context.Context) Ovh_iploadbalancingMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_iploadbalancingMapOutput)
}

type Ovh_iploadbalancingOutput struct{ *pulumi.OutputState }

func (Ovh_iploadbalancingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Ovh_iploadbalancing)(nil))
}

func (o Ovh_iploadbalancingOutput) ToOvh_iploadbalancingOutput() Ovh_iploadbalancingOutput {
	return o
}

func (o Ovh_iploadbalancingOutput) ToOvh_iploadbalancingOutputWithContext(ctx context.Context) Ovh_iploadbalancingOutput {
	return o
}

func (o Ovh_iploadbalancingOutput) ToOvh_iploadbalancingPtrOutput() Ovh_iploadbalancingPtrOutput {
	return o.ToOvh_iploadbalancingPtrOutputWithContext(context.Background())
}

func (o Ovh_iploadbalancingOutput) ToOvh_iploadbalancingPtrOutputWithContext(ctx context.Context) Ovh_iploadbalancingPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Ovh_iploadbalancing) *Ovh_iploadbalancing {
		return &v
	}).(Ovh_iploadbalancingPtrOutput)
}

type Ovh_iploadbalancingPtrOutput struct{ *pulumi.OutputState }

func (Ovh_iploadbalancingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Ovh_iploadbalancing)(nil))
}

func (o Ovh_iploadbalancingPtrOutput) ToOvh_iploadbalancingPtrOutput() Ovh_iploadbalancingPtrOutput {
	return o
}

func (o Ovh_iploadbalancingPtrOutput) ToOvh_iploadbalancingPtrOutputWithContext(ctx context.Context) Ovh_iploadbalancingPtrOutput {
	return o
}

func (o Ovh_iploadbalancingPtrOutput) Elem() Ovh_iploadbalancingOutput {
	return o.ApplyT(func(v *Ovh_iploadbalancing) Ovh_iploadbalancing {
		if v != nil {
			return *v
		}
		var ret Ovh_iploadbalancing
		return ret
	}).(Ovh_iploadbalancingOutput)
}

type Ovh_iploadbalancingArrayOutput struct{ *pulumi.OutputState }

func (Ovh_iploadbalancingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Ovh_iploadbalancing)(nil))
}

func (o Ovh_iploadbalancingArrayOutput) ToOvh_iploadbalancingArrayOutput() Ovh_iploadbalancingArrayOutput {
	return o
}

func (o Ovh_iploadbalancingArrayOutput) ToOvh_iploadbalancingArrayOutputWithContext(ctx context.Context) Ovh_iploadbalancingArrayOutput {
	return o
}

func (o Ovh_iploadbalancingArrayOutput) Index(i pulumi.IntInput) Ovh_iploadbalancingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Ovh_iploadbalancing {
		return vs[0].([]Ovh_iploadbalancing)[vs[1].(int)]
	}).(Ovh_iploadbalancingOutput)
}

type Ovh_iploadbalancingMapOutput struct{ *pulumi.OutputState }

func (Ovh_iploadbalancingMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]Ovh_iploadbalancing)(nil))
}

func (o Ovh_iploadbalancingMapOutput) ToOvh_iploadbalancingMapOutput() Ovh_iploadbalancingMapOutput {
	return o
}

func (o Ovh_iploadbalancingMapOutput) ToOvh_iploadbalancingMapOutputWithContext(ctx context.Context) Ovh_iploadbalancingMapOutput {
	return o
}

func (o Ovh_iploadbalancingMapOutput) MapIndex(k pulumi.StringInput) Ovh_iploadbalancingOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) Ovh_iploadbalancing {
		return vs[0].(map[string]Ovh_iploadbalancing)[vs[1].(string)]
	}).(Ovh_iploadbalancingOutput)
}

func init() {
	pulumi.RegisterOutputType(Ovh_iploadbalancingOutput{})
	pulumi.RegisterOutputType(Ovh_iploadbalancingPtrOutput{})
	pulumi.RegisterOutputType(Ovh_iploadbalancingArrayOutput{})
	pulumi.RegisterOutputType(Ovh_iploadbalancingMapOutput{})
}
