// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Ovh_cloud_project_containerregistry struct {
	pulumi.CustomResourceState

	// Registry creation date
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Registry name
	Name pulumi.StringOutput `pulumi:"name"`
	// Plan ID of the registry.
	PlanId pulumi.StringOutput `pulumi:"planId"`
	// Plan of the registry
	Plans Ovh_cloud_project_containerregistryPlanArrayOutput `pulumi:"plans"`
	// Project ID of your registry
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Region of the registry.
	Region      pulumi.StringOutput `pulumi:"region"`
	ServiceName pulumi.StringOutput `pulumi:"serviceName"`
	// Current size of the registry (bytes)
	Size pulumi.IntOutput `pulumi:"size"`
	// Registry status
	Status pulumi.StringOutput `pulumi:"status"`
	// Registry last update date
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Access url of the registry
	Url pulumi.StringOutput `pulumi:"url"`
	// Version of your registry
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewOvh_cloud_project_containerregistry registers a new resource with the given unique name, arguments, and options.
func NewOvh_cloud_project_containerregistry(ctx *pulumi.Context,
	name string, args *Ovh_cloud_project_containerregistryArgs, opts ...pulumi.ResourceOption) (*Ovh_cloud_project_containerregistry, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.ServiceName == nil {
		return nil, errors.New("invalid value for required argument 'ServiceName'")
	}
	var resource Ovh_cloud_project_containerregistry
	err := ctx.RegisterResource("ovh:index/ovh_cloud_project_containerregistry:ovh_cloud_project_containerregistry", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOvh_cloud_project_containerregistry gets an existing Ovh_cloud_project_containerregistry resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOvh_cloud_project_containerregistry(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *Ovh_cloud_project_containerregistryState, opts ...pulumi.ResourceOption) (*Ovh_cloud_project_containerregistry, error) {
	var resource Ovh_cloud_project_containerregistry
	err := ctx.ReadResource("ovh:index/ovh_cloud_project_containerregistry:ovh_cloud_project_containerregistry", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Ovh_cloud_project_containerregistry resources.
type ovh_cloud_project_containerregistryState struct {
	// Registry creation date
	CreatedAt *string `pulumi:"createdAt"`
	// Registry name
	Name *string `pulumi:"name"`
	// Plan ID of the registry.
	PlanId *string `pulumi:"planId"`
	// Plan of the registry
	Plans []Ovh_cloud_project_containerregistryPlan `pulumi:"plans"`
	// Project ID of your registry
	ProjectId *string `pulumi:"projectId"`
	// Region of the registry.
	Region      *string `pulumi:"region"`
	ServiceName *string `pulumi:"serviceName"`
	// Current size of the registry (bytes)
	Size *int `pulumi:"size"`
	// Registry status
	Status *string `pulumi:"status"`
	// Registry last update date
	UpdatedAt *string `pulumi:"updatedAt"`
	// Access url of the registry
	Url *string `pulumi:"url"`
	// Version of your registry
	Version *string `pulumi:"version"`
}

type Ovh_cloud_project_containerregistryState struct {
	// Registry creation date
	CreatedAt pulumi.StringPtrInput
	// Registry name
	Name pulumi.StringPtrInput
	// Plan ID of the registry.
	PlanId pulumi.StringPtrInput
	// Plan of the registry
	Plans Ovh_cloud_project_containerregistryPlanArrayInput
	// Project ID of your registry
	ProjectId pulumi.StringPtrInput
	// Region of the registry.
	Region      pulumi.StringPtrInput
	ServiceName pulumi.StringPtrInput
	// Current size of the registry (bytes)
	Size pulumi.IntPtrInput
	// Registry status
	Status pulumi.StringPtrInput
	// Registry last update date
	UpdatedAt pulumi.StringPtrInput
	// Access url of the registry
	Url pulumi.StringPtrInput
	// Version of your registry
	Version pulumi.StringPtrInput
}

func (Ovh_cloud_project_containerregistryState) ElementType() reflect.Type {
	return reflect.TypeOf((*ovh_cloud_project_containerregistryState)(nil)).Elem()
}

type ovh_cloud_project_containerregistryArgs struct {
	// Registry name
	Name *string `pulumi:"name"`
	// Plan ID of the registry.
	PlanId *string `pulumi:"planId"`
	// Region of the registry.
	Region      string `pulumi:"region"`
	ServiceName string `pulumi:"serviceName"`
}

// The set of arguments for constructing a Ovh_cloud_project_containerregistry resource.
type Ovh_cloud_project_containerregistryArgs struct {
	// Registry name
	Name pulumi.StringPtrInput
	// Plan ID of the registry.
	PlanId pulumi.StringPtrInput
	// Region of the registry.
	Region      pulumi.StringInput
	ServiceName pulumi.StringInput
}

func (Ovh_cloud_project_containerregistryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ovh_cloud_project_containerregistryArgs)(nil)).Elem()
}

type Ovh_cloud_project_containerregistryInput interface {
	pulumi.Input

	ToOvh_cloud_project_containerregistryOutput() Ovh_cloud_project_containerregistryOutput
	ToOvh_cloud_project_containerregistryOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryOutput
}

func (*Ovh_cloud_project_containerregistry) ElementType() reflect.Type {
	return reflect.TypeOf((*Ovh_cloud_project_containerregistry)(nil))
}

func (i *Ovh_cloud_project_containerregistry) ToOvh_cloud_project_containerregistryOutput() Ovh_cloud_project_containerregistryOutput {
	return i.ToOvh_cloud_project_containerregistryOutputWithContext(context.Background())
}

func (i *Ovh_cloud_project_containerregistry) ToOvh_cloud_project_containerregistryOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_project_containerregistryOutput)
}

func (i *Ovh_cloud_project_containerregistry) ToOvh_cloud_project_containerregistryPtrOutput() Ovh_cloud_project_containerregistryPtrOutput {
	return i.ToOvh_cloud_project_containerregistryPtrOutputWithContext(context.Background())
}

func (i *Ovh_cloud_project_containerregistry) ToOvh_cloud_project_containerregistryPtrOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_project_containerregistryPtrOutput)
}

type Ovh_cloud_project_containerregistryPtrInput interface {
	pulumi.Input

	ToOvh_cloud_project_containerregistryPtrOutput() Ovh_cloud_project_containerregistryPtrOutput
	ToOvh_cloud_project_containerregistryPtrOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryPtrOutput
}

type ovh_cloud_project_containerregistryPtrType Ovh_cloud_project_containerregistryArgs

func (*ovh_cloud_project_containerregistryPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Ovh_cloud_project_containerregistry)(nil))
}

func (i *ovh_cloud_project_containerregistryPtrType) ToOvh_cloud_project_containerregistryPtrOutput() Ovh_cloud_project_containerregistryPtrOutput {
	return i.ToOvh_cloud_project_containerregistryPtrOutputWithContext(context.Background())
}

func (i *ovh_cloud_project_containerregistryPtrType) ToOvh_cloud_project_containerregistryPtrOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_project_containerregistryPtrOutput)
}

// Ovh_cloud_project_containerregistryArrayInput is an input type that accepts Ovh_cloud_project_containerregistryArray and Ovh_cloud_project_containerregistryArrayOutput values.
// You can construct a concrete instance of `Ovh_cloud_project_containerregistryArrayInput` via:
//
//          Ovh_cloud_project_containerregistryArray{ Ovh_cloud_project_containerregistryArgs{...} }
type Ovh_cloud_project_containerregistryArrayInput interface {
	pulumi.Input

	ToOvh_cloud_project_containerregistryArrayOutput() Ovh_cloud_project_containerregistryArrayOutput
	ToOvh_cloud_project_containerregistryArrayOutputWithContext(context.Context) Ovh_cloud_project_containerregistryArrayOutput
}

type Ovh_cloud_project_containerregistryArray []Ovh_cloud_project_containerregistryInput

func (Ovh_cloud_project_containerregistryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Ovh_cloud_project_containerregistry)(nil)).Elem()
}

func (i Ovh_cloud_project_containerregistryArray) ToOvh_cloud_project_containerregistryArrayOutput() Ovh_cloud_project_containerregistryArrayOutput {
	return i.ToOvh_cloud_project_containerregistryArrayOutputWithContext(context.Background())
}

func (i Ovh_cloud_project_containerregistryArray) ToOvh_cloud_project_containerregistryArrayOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_project_containerregistryArrayOutput)
}

// Ovh_cloud_project_containerregistryMapInput is an input type that accepts Ovh_cloud_project_containerregistryMap and Ovh_cloud_project_containerregistryMapOutput values.
// You can construct a concrete instance of `Ovh_cloud_project_containerregistryMapInput` via:
//
//          Ovh_cloud_project_containerregistryMap{ "key": Ovh_cloud_project_containerregistryArgs{...} }
type Ovh_cloud_project_containerregistryMapInput interface {
	pulumi.Input

	ToOvh_cloud_project_containerregistryMapOutput() Ovh_cloud_project_containerregistryMapOutput
	ToOvh_cloud_project_containerregistryMapOutputWithContext(context.Context) Ovh_cloud_project_containerregistryMapOutput
}

type Ovh_cloud_project_containerregistryMap map[string]Ovh_cloud_project_containerregistryInput

func (Ovh_cloud_project_containerregistryMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Ovh_cloud_project_containerregistry)(nil)).Elem()
}

func (i Ovh_cloud_project_containerregistryMap) ToOvh_cloud_project_containerregistryMapOutput() Ovh_cloud_project_containerregistryMapOutput {
	return i.ToOvh_cloud_project_containerregistryMapOutputWithContext(context.Background())
}

func (i Ovh_cloud_project_containerregistryMap) ToOvh_cloud_project_containerregistryMapOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_cloud_project_containerregistryMapOutput)
}

type Ovh_cloud_project_containerregistryOutput struct{ *pulumi.OutputState }

func (Ovh_cloud_project_containerregistryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Ovh_cloud_project_containerregistry)(nil))
}

func (o Ovh_cloud_project_containerregistryOutput) ToOvh_cloud_project_containerregistryOutput() Ovh_cloud_project_containerregistryOutput {
	return o
}

func (o Ovh_cloud_project_containerregistryOutput) ToOvh_cloud_project_containerregistryOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryOutput {
	return o
}

func (o Ovh_cloud_project_containerregistryOutput) ToOvh_cloud_project_containerregistryPtrOutput() Ovh_cloud_project_containerregistryPtrOutput {
	return o.ToOvh_cloud_project_containerregistryPtrOutputWithContext(context.Background())
}

func (o Ovh_cloud_project_containerregistryOutput) ToOvh_cloud_project_containerregistryPtrOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Ovh_cloud_project_containerregistry) *Ovh_cloud_project_containerregistry {
		return &v
	}).(Ovh_cloud_project_containerregistryPtrOutput)
}

type Ovh_cloud_project_containerregistryPtrOutput struct{ *pulumi.OutputState }

func (Ovh_cloud_project_containerregistryPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Ovh_cloud_project_containerregistry)(nil))
}

func (o Ovh_cloud_project_containerregistryPtrOutput) ToOvh_cloud_project_containerregistryPtrOutput() Ovh_cloud_project_containerregistryPtrOutput {
	return o
}

func (o Ovh_cloud_project_containerregistryPtrOutput) ToOvh_cloud_project_containerregistryPtrOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryPtrOutput {
	return o
}

func (o Ovh_cloud_project_containerregistryPtrOutput) Elem() Ovh_cloud_project_containerregistryOutput {
	return o.ApplyT(func(v *Ovh_cloud_project_containerregistry) Ovh_cloud_project_containerregistry {
		if v != nil {
			return *v
		}
		var ret Ovh_cloud_project_containerregistry
		return ret
	}).(Ovh_cloud_project_containerregistryOutput)
}

type Ovh_cloud_project_containerregistryArrayOutput struct{ *pulumi.OutputState }

func (Ovh_cloud_project_containerregistryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Ovh_cloud_project_containerregistry)(nil))
}

func (o Ovh_cloud_project_containerregistryArrayOutput) ToOvh_cloud_project_containerregistryArrayOutput() Ovh_cloud_project_containerregistryArrayOutput {
	return o
}

func (o Ovh_cloud_project_containerregistryArrayOutput) ToOvh_cloud_project_containerregistryArrayOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryArrayOutput {
	return o
}

func (o Ovh_cloud_project_containerregistryArrayOutput) Index(i pulumi.IntInput) Ovh_cloud_project_containerregistryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Ovh_cloud_project_containerregistry {
		return vs[0].([]Ovh_cloud_project_containerregistry)[vs[1].(int)]
	}).(Ovh_cloud_project_containerregistryOutput)
}

type Ovh_cloud_project_containerregistryMapOutput struct{ *pulumi.OutputState }

func (Ovh_cloud_project_containerregistryMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]Ovh_cloud_project_containerregistry)(nil))
}

func (o Ovh_cloud_project_containerregistryMapOutput) ToOvh_cloud_project_containerregistryMapOutput() Ovh_cloud_project_containerregistryMapOutput {
	return o
}

func (o Ovh_cloud_project_containerregistryMapOutput) ToOvh_cloud_project_containerregistryMapOutputWithContext(ctx context.Context) Ovh_cloud_project_containerregistryMapOutput {
	return o
}

func (o Ovh_cloud_project_containerregistryMapOutput) MapIndex(k pulumi.StringInput) Ovh_cloud_project_containerregistryOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) Ovh_cloud_project_containerregistry {
		return vs[0].(map[string]Ovh_cloud_project_containerregistry)[vs[1].(string)]
	}).(Ovh_cloud_project_containerregistryOutput)
}

func init() {
	pulumi.RegisterOutputType(Ovh_cloud_project_containerregistryOutput{})
	pulumi.RegisterOutputType(Ovh_cloud_project_containerregistryPtrOutput{})
	pulumi.RegisterOutputType(Ovh_cloud_project_containerregistryArrayOutput{})
	pulumi.RegisterOutputType(Ovh_cloud_project_containerregistryMapOutput{})
}
