// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Ovh_ip_reverse struct {
	pulumi.CustomResourceState

	Ip        pulumi.StringOutput `pulumi:"ip"`
	IpReverse pulumi.StringOutput `pulumi:"ipReverse"`
	Reverse   pulumi.StringOutput `pulumi:"reverse"`
}

// NewOvh_ip_reverse registers a new resource with the given unique name, arguments, and options.
func NewOvh_ip_reverse(ctx *pulumi.Context,
	name string, args *Ovh_ip_reverseArgs, opts ...pulumi.ResourceOption) (*Ovh_ip_reverse, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Ip == nil {
		return nil, errors.New("invalid value for required argument 'Ip'")
	}
	if args.IpReverse == nil {
		return nil, errors.New("invalid value for required argument 'IpReverse'")
	}
	if args.Reverse == nil {
		return nil, errors.New("invalid value for required argument 'Reverse'")
	}
	var resource Ovh_ip_reverse
	err := ctx.RegisterResource("ovh:index/ovh_ip_reverse:ovh_ip_reverse", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOvh_ip_reverse gets an existing Ovh_ip_reverse resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOvh_ip_reverse(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *Ovh_ip_reverseState, opts ...pulumi.ResourceOption) (*Ovh_ip_reverse, error) {
	var resource Ovh_ip_reverse
	err := ctx.ReadResource("ovh:index/ovh_ip_reverse:ovh_ip_reverse", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Ovh_ip_reverse resources.
type ovh_ip_reverseState struct {
	Ip        *string `pulumi:"ip"`
	IpReverse *string `pulumi:"ipReverse"`
	Reverse   *string `pulumi:"reverse"`
}

type Ovh_ip_reverseState struct {
	Ip        pulumi.StringPtrInput
	IpReverse pulumi.StringPtrInput
	Reverse   pulumi.StringPtrInput
}

func (Ovh_ip_reverseState) ElementType() reflect.Type {
	return reflect.TypeOf((*ovh_ip_reverseState)(nil)).Elem()
}

type ovh_ip_reverseArgs struct {
	Ip        string `pulumi:"ip"`
	IpReverse string `pulumi:"ipReverse"`
	Reverse   string `pulumi:"reverse"`
}

// The set of arguments for constructing a Ovh_ip_reverse resource.
type Ovh_ip_reverseArgs struct {
	Ip        pulumi.StringInput
	IpReverse pulumi.StringInput
	Reverse   pulumi.StringInput
}

func (Ovh_ip_reverseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ovh_ip_reverseArgs)(nil)).Elem()
}

type Ovh_ip_reverseInput interface {
	pulumi.Input

	ToOvh_ip_reverseOutput() Ovh_ip_reverseOutput
	ToOvh_ip_reverseOutputWithContext(ctx context.Context) Ovh_ip_reverseOutput
}

func (*Ovh_ip_reverse) ElementType() reflect.Type {
	return reflect.TypeOf((*Ovh_ip_reverse)(nil))
}

func (i *Ovh_ip_reverse) ToOvh_ip_reverseOutput() Ovh_ip_reverseOutput {
	return i.ToOvh_ip_reverseOutputWithContext(context.Background())
}

func (i *Ovh_ip_reverse) ToOvh_ip_reverseOutputWithContext(ctx context.Context) Ovh_ip_reverseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_ip_reverseOutput)
}

func (i *Ovh_ip_reverse) ToOvh_ip_reversePtrOutput() Ovh_ip_reversePtrOutput {
	return i.ToOvh_ip_reversePtrOutputWithContext(context.Background())
}

func (i *Ovh_ip_reverse) ToOvh_ip_reversePtrOutputWithContext(ctx context.Context) Ovh_ip_reversePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_ip_reversePtrOutput)
}

type Ovh_ip_reversePtrInput interface {
	pulumi.Input

	ToOvh_ip_reversePtrOutput() Ovh_ip_reversePtrOutput
	ToOvh_ip_reversePtrOutputWithContext(ctx context.Context) Ovh_ip_reversePtrOutput
}

type ovh_ip_reversePtrType Ovh_ip_reverseArgs

func (*ovh_ip_reversePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Ovh_ip_reverse)(nil))
}

func (i *ovh_ip_reversePtrType) ToOvh_ip_reversePtrOutput() Ovh_ip_reversePtrOutput {
	return i.ToOvh_ip_reversePtrOutputWithContext(context.Background())
}

func (i *ovh_ip_reversePtrType) ToOvh_ip_reversePtrOutputWithContext(ctx context.Context) Ovh_ip_reversePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_ip_reversePtrOutput)
}

// Ovh_ip_reverseArrayInput is an input type that accepts Ovh_ip_reverseArray and Ovh_ip_reverseArrayOutput values.
// You can construct a concrete instance of `Ovh_ip_reverseArrayInput` via:
//
//          Ovh_ip_reverseArray{ Ovh_ip_reverseArgs{...} }
type Ovh_ip_reverseArrayInput interface {
	pulumi.Input

	ToOvh_ip_reverseArrayOutput() Ovh_ip_reverseArrayOutput
	ToOvh_ip_reverseArrayOutputWithContext(context.Context) Ovh_ip_reverseArrayOutput
}

type Ovh_ip_reverseArray []Ovh_ip_reverseInput

func (Ovh_ip_reverseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Ovh_ip_reverse)(nil)).Elem()
}

func (i Ovh_ip_reverseArray) ToOvh_ip_reverseArrayOutput() Ovh_ip_reverseArrayOutput {
	return i.ToOvh_ip_reverseArrayOutputWithContext(context.Background())
}

func (i Ovh_ip_reverseArray) ToOvh_ip_reverseArrayOutputWithContext(ctx context.Context) Ovh_ip_reverseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_ip_reverseArrayOutput)
}

// Ovh_ip_reverseMapInput is an input type that accepts Ovh_ip_reverseMap and Ovh_ip_reverseMapOutput values.
// You can construct a concrete instance of `Ovh_ip_reverseMapInput` via:
//
//          Ovh_ip_reverseMap{ "key": Ovh_ip_reverseArgs{...} }
type Ovh_ip_reverseMapInput interface {
	pulumi.Input

	ToOvh_ip_reverseMapOutput() Ovh_ip_reverseMapOutput
	ToOvh_ip_reverseMapOutputWithContext(context.Context) Ovh_ip_reverseMapOutput
}

type Ovh_ip_reverseMap map[string]Ovh_ip_reverseInput

func (Ovh_ip_reverseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Ovh_ip_reverse)(nil)).Elem()
}

func (i Ovh_ip_reverseMap) ToOvh_ip_reverseMapOutput() Ovh_ip_reverseMapOutput {
	return i.ToOvh_ip_reverseMapOutputWithContext(context.Background())
}

func (i Ovh_ip_reverseMap) ToOvh_ip_reverseMapOutputWithContext(ctx context.Context) Ovh_ip_reverseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Ovh_ip_reverseMapOutput)
}

type Ovh_ip_reverseOutput struct{ *pulumi.OutputState }

func (Ovh_ip_reverseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Ovh_ip_reverse)(nil))
}

func (o Ovh_ip_reverseOutput) ToOvh_ip_reverseOutput() Ovh_ip_reverseOutput {
	return o
}

func (o Ovh_ip_reverseOutput) ToOvh_ip_reverseOutputWithContext(ctx context.Context) Ovh_ip_reverseOutput {
	return o
}

func (o Ovh_ip_reverseOutput) ToOvh_ip_reversePtrOutput() Ovh_ip_reversePtrOutput {
	return o.ToOvh_ip_reversePtrOutputWithContext(context.Background())
}

func (o Ovh_ip_reverseOutput) ToOvh_ip_reversePtrOutputWithContext(ctx context.Context) Ovh_ip_reversePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Ovh_ip_reverse) *Ovh_ip_reverse {
		return &v
	}).(Ovh_ip_reversePtrOutput)
}

type Ovh_ip_reversePtrOutput struct{ *pulumi.OutputState }

func (Ovh_ip_reversePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Ovh_ip_reverse)(nil))
}

func (o Ovh_ip_reversePtrOutput) ToOvh_ip_reversePtrOutput() Ovh_ip_reversePtrOutput {
	return o
}

func (o Ovh_ip_reversePtrOutput) ToOvh_ip_reversePtrOutputWithContext(ctx context.Context) Ovh_ip_reversePtrOutput {
	return o
}

func (o Ovh_ip_reversePtrOutput) Elem() Ovh_ip_reverseOutput {
	return o.ApplyT(func(v *Ovh_ip_reverse) Ovh_ip_reverse {
		if v != nil {
			return *v
		}
		var ret Ovh_ip_reverse
		return ret
	}).(Ovh_ip_reverseOutput)
}

type Ovh_ip_reverseArrayOutput struct{ *pulumi.OutputState }

func (Ovh_ip_reverseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Ovh_ip_reverse)(nil))
}

func (o Ovh_ip_reverseArrayOutput) ToOvh_ip_reverseArrayOutput() Ovh_ip_reverseArrayOutput {
	return o
}

func (o Ovh_ip_reverseArrayOutput) ToOvh_ip_reverseArrayOutputWithContext(ctx context.Context) Ovh_ip_reverseArrayOutput {
	return o
}

func (o Ovh_ip_reverseArrayOutput) Index(i pulumi.IntInput) Ovh_ip_reverseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Ovh_ip_reverse {
		return vs[0].([]Ovh_ip_reverse)[vs[1].(int)]
	}).(Ovh_ip_reverseOutput)
}

type Ovh_ip_reverseMapOutput struct{ *pulumi.OutputState }

func (Ovh_ip_reverseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]Ovh_ip_reverse)(nil))
}

func (o Ovh_ip_reverseMapOutput) ToOvh_ip_reverseMapOutput() Ovh_ip_reverseMapOutput {
	return o
}

func (o Ovh_ip_reverseMapOutput) ToOvh_ip_reverseMapOutputWithContext(ctx context.Context) Ovh_ip_reverseMapOutput {
	return o
}

func (o Ovh_ip_reverseMapOutput) MapIndex(k pulumi.StringInput) Ovh_ip_reverseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) Ovh_ip_reverse {
		return vs[0].(map[string]Ovh_ip_reverse)[vs[1].(string)]
	}).(Ovh_ip_reverseOutput)
}

func init() {
	pulumi.RegisterOutputType(Ovh_ip_reverseOutput{})
	pulumi.RegisterOutputType(Ovh_ip_reversePtrOutput{})
	pulumi.RegisterOutputType(Ovh_ip_reverseArrayOutput{})
	pulumi.RegisterOutputType(Ovh_ip_reverseMapOutput{})
}
