// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh.Outputs
{

    [OutputType]
    public sealed class DedicatedServerInstallTaskDetails
    {
        public readonly string? ChangeLog;
        public readonly string? CustomHostname;
        public readonly int? DiskGroupId;
        public readonly bool? InstallRtm;
        public readonly bool? InstallSqlServer;
        public readonly string? Language;
        public readonly bool? NoRaid;
        public readonly string? PostInstallationScriptLink;
        public readonly string? PostInstallationScriptReturn;
        public readonly bool? ResetHwRaid;
        public readonly int? SoftRaidDevices;
        public readonly string? SshKeyName;
        public readonly bool? UseDistribKernel;
        public readonly bool? UseSpla;

        [OutputConstructor]
        private DedicatedServerInstallTaskDetails(
            string? changeLog,

            string? customHostname,

            int? diskGroupId,

            bool? installRtm,

            bool? installSqlServer,

            string? language,

            bool? noRaid,

            string? postInstallationScriptLink,

            string? postInstallationScriptReturn,

            bool? resetHwRaid,

            int? softRaidDevices,

            string? sshKeyName,

            bool? useDistribKernel,

            bool? useSpla)
        {
            ChangeLog = changeLog;
            CustomHostname = customHostname;
            DiskGroupId = diskGroupId;
            InstallRtm = installRtm;
            InstallSqlServer = installSqlServer;
            Language = language;
            NoRaid = noRaid;
            PostInstallationScriptLink = postInstallationScriptLink;
            PostInstallationScriptReturn = postInstallationScriptReturn;
            ResetHwRaid = resetHwRaid;
            SoftRaidDevices = softRaidDevices;
            SshKeyName = sshKeyName;
            UseDistribKernel = useDistribKernel;
            UseSpla = useSpla;
        }
    }
}
