// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh.Outputs
{

    [OutputType]
    public sealed class Ovh_dbaas_logs_inputConfigurationLogstash
    {
        public readonly string? FilterSection;
        public readonly string InputSection;
        public readonly string? PatternSection;

        [OutputConstructor]
        private Ovh_dbaas_logs_inputConfigurationLogstash(
            string? filterSection,

            string inputSection,

            string? patternSection)
        {
            FilterSection = filterSection;
            InputSection = inputSection;
            PatternSection = patternSection;
        }
    }
}
