# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetOvh_Me_Ssh_KeyResult',
    'AwaitableGetOvh_Me_Ssh_KeyResult',
    'get_ovh__me__ssh__key',
    'get_ovh__me__ssh__key_output',
]

@pulumi.output_type
class GetOvh_Me_Ssh_KeyResult:
    """
    A collection of values returned by getOvh_Me_Ssh_Key.
    """
    def __init__(__self__, default=None, id=None, key=None, key_name=None):
        if default and not isinstance(default, bool):
            raise TypeError("Expected argument 'default' to be a bool")
        pulumi.set(__self__, "default", default)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if key and not isinstance(key, str):
            raise TypeError("Expected argument 'key' to be a str")
        pulumi.set(__self__, "key", key)
        if key_name and not isinstance(key_name, str):
            raise TypeError("Expected argument 'key_name' to be a str")
        pulumi.set(__self__, "key_name", key_name)

    @property
    @pulumi.getter
    def default(self) -> bool:
        return pulumi.get(self, "default")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def key(self) -> str:
        return pulumi.get(self, "key")

    @property
    @pulumi.getter(name="keyName")
    def key_name(self) -> str:
        return pulumi.get(self, "key_name")


class AwaitableGetOvh_Me_Ssh_KeyResult(GetOvh_Me_Ssh_KeyResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOvh_Me_Ssh_KeyResult(
            default=self.default,
            id=self.id,
            key=self.key,
            key_name=self.key_name)


def get_ovh__me__ssh__key(key_name: Optional[str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOvh_Me_Ssh_KeyResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['keyName'] = key_name
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('ovh:index/getOvh_Me_Ssh_Key:getOvh_Me_Ssh_Key', __args__, opts=opts, typ=GetOvh_Me_Ssh_KeyResult).value

    return AwaitableGetOvh_Me_Ssh_KeyResult(
        default=__ret__.default,
        id=__ret__.id,
        key=__ret__.key,
        key_name=__ret__.key_name)


@_utilities.lift_output_func(get_ovh__me__ssh__key)
def get_ovh__me__ssh__key_output(key_name: Optional[pulumi.Input[str]] = None,
                                 opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetOvh_Me_Ssh_KeyResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
