# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetOvh_VracksResult',
    'AwaitableGetOvh_VracksResult',
    'get_ovh__vracks',
]

@pulumi.output_type
class GetOvh_VracksResult:
    """
    A collection of values returned by getOvh_Vracks.
    """
    def __init__(__self__, id=None, results=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if results and not isinstance(results, list):
            raise TypeError("Expected argument 'results' to be a list")
        pulumi.set(__self__, "results", results)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def results(self) -> Sequence[str]:
        return pulumi.get(self, "results")


class AwaitableGetOvh_VracksResult(GetOvh_VracksResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOvh_VracksResult(
            id=self.id,
            results=self.results)


def get_ovh__vracks(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOvh_VracksResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('ovh:index/getOvh_Vracks:getOvh_Vracks', __args__, opts=opts, typ=GetOvh_VracksResult).value

    return AwaitableGetOvh_VracksResult(
        id=__ret__.id,
        results=__ret__.results)
