// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface Ovh_cloud_projectOrder {
    date?: pulumi.Input<string>;
    details?: pulumi.Input<pulumi.Input<inputs.Ovh_cloud_projectOrderDetail>[]>;
    expirationDate?: pulumi.Input<string>;
    orderId?: pulumi.Input<number>;
}

export interface Ovh_cloud_projectOrderDetail {
    description?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    orderDetailId?: pulumi.Input<number>;
    quantity?: pulumi.Input<string>;
}

export interface Ovh_cloud_projectPlan {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_cloud_projectPlanConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_cloud_projectPlanConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_cloud_projectPlanOption {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_cloud_projectPlanOptionConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_cloud_projectPlanOptionConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_cloud_project_containerregistryPlan {
    code?: pulumi.Input<string>;
    createdAt?: pulumi.Input<string>;
    features?: pulumi.Input<pulumi.Input<inputs.Ovh_cloud_project_containerregistryPlanFeature>[]>;
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    registryLimits?: pulumi.Input<pulumi.Input<inputs.Ovh_cloud_project_containerregistryPlanRegistryLimit>[]>;
    updatedAt?: pulumi.Input<string>;
}

export interface Ovh_cloud_project_containerregistryPlanFeature {
    vulnerability?: pulumi.Input<boolean>;
}

export interface Ovh_cloud_project_containerregistryPlanRegistryLimit {
    imageStorage?: pulumi.Input<number>;
    parallelRequest?: pulumi.Input<number>;
}

export interface Ovh_cloud_project_network_privateRegionsAttribute {
    openstackid?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    status: pulumi.Input<string>;
}

export interface Ovh_cloud_project_network_privateRegionsStatus {
    region?: pulumi.Input<string>;
    status: pulumi.Input<string>;
}

export interface Ovh_cloud_project_network_private_subnetIpPool {
    dhcp?: pulumi.Input<boolean>;
    end?: pulumi.Input<string>;
    network?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    start?: pulumi.Input<string>;
}

export interface Ovh_cloud_project_userRole {
    description?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    permissions?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface Ovh_dbaas_logs_inputConfiguration {
    flowgger?: pulumi.Input<inputs.Ovh_dbaas_logs_inputConfigurationFlowgger>;
    logstash?: pulumi.Input<inputs.Ovh_dbaas_logs_inputConfigurationLogstash>;
}

export interface Ovh_dbaas_logs_inputConfigurationFlowgger {
    logFormat: pulumi.Input<string>;
    logFraming: pulumi.Input<string>;
}

export interface Ovh_dbaas_logs_inputConfigurationLogstash {
    filterSection?: pulumi.Input<string>;
    inputSection: pulumi.Input<string>;
    patternSection?: pulumi.Input<string>;
}

export interface Ovh_dedicated_server_install_taskDetails {
    /**
     * @deprecated field is not used anymore
     */
    changeLog?: pulumi.Input<string>;
    customHostname?: pulumi.Input<string>;
    diskGroupId?: pulumi.Input<number>;
    installRtm?: pulumi.Input<boolean>;
    installSqlServer?: pulumi.Input<boolean>;
    language?: pulumi.Input<string>;
    noRaid?: pulumi.Input<boolean>;
    postInstallationScriptLink?: pulumi.Input<string>;
    postInstallationScriptReturn?: pulumi.Input<string>;
    resetHwRaid?: pulumi.Input<boolean>;
    softRaidDevices?: pulumi.Input<number>;
    sshKeyName?: pulumi.Input<string>;
    useDistribKernel?: pulumi.Input<boolean>;
    useSpla?: pulumi.Input<boolean>;
}

export interface Ovh_domain_zoneOrder {
    date?: pulumi.Input<string>;
    details?: pulumi.Input<pulumi.Input<inputs.Ovh_domain_zoneOrderDetail>[]>;
    expirationDate?: pulumi.Input<string>;
    orderId?: pulumi.Input<number>;
}

export interface Ovh_domain_zoneOrderDetail {
    description?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    orderDetailId?: pulumi.Input<number>;
    quantity?: pulumi.Input<string>;
}

export interface Ovh_domain_zonePlan {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_domain_zonePlanConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_domain_zonePlanConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_domain_zonePlanOption {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_domain_zonePlanOptionConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_domain_zonePlanOptionConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_ip_serviceOrder {
    date?: pulumi.Input<string>;
    details?: pulumi.Input<pulumi.Input<inputs.Ovh_ip_serviceOrderDetail>[]>;
    expirationDate?: pulumi.Input<string>;
    orderId?: pulumi.Input<number>;
}

export interface Ovh_ip_serviceOrderDetail {
    description?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    orderDetailId?: pulumi.Input<number>;
    quantity?: pulumi.Input<string>;
}

export interface Ovh_ip_servicePlan {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_ip_servicePlanConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_ip_servicePlanConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_ip_servicePlanOption {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_ip_servicePlanOptionConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_ip_servicePlanOptionConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_ip_serviceRoutedTo {
    serviceName?: pulumi.Input<string>;
}

export interface Ovh_iploadbalancingOrder {
    date?: pulumi.Input<string>;
    details?: pulumi.Input<pulumi.Input<inputs.Ovh_iploadbalancingOrderDetail>[]>;
    expirationDate?: pulumi.Input<string>;
    orderId?: pulumi.Input<number>;
}

export interface Ovh_iploadbalancingOrderDetail {
    description?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    orderDetailId?: pulumi.Input<number>;
    quantity?: pulumi.Input<string>;
}

export interface Ovh_iploadbalancingOrderableZone {
    name?: pulumi.Input<string>;
    planCode?: pulumi.Input<string>;
}

export interface Ovh_iploadbalancingPlan {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_iploadbalancingPlanConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_iploadbalancingPlanConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_iploadbalancingPlanOption {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_iploadbalancingPlanOptionConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_iploadbalancingPlanOptionConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_iploadbalancing_http_farmProbe {
    forceSsl?: pulumi.Input<boolean>;
    interval?: pulumi.Input<number>;
    match?: pulumi.Input<string>;
    method?: pulumi.Input<string>;
    negate?: pulumi.Input<boolean>;
    pattern?: pulumi.Input<string>;
    port?: pulumi.Input<number>;
    type: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface Ovh_iploadbalancing_http_routeAction {
    status?: pulumi.Input<number>;
    target?: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface Ovh_iploadbalancing_http_routeRule {
    field?: pulumi.Input<string>;
    match?: pulumi.Input<string>;
    negate?: pulumi.Input<boolean>;
    pattern?: pulumi.Input<string>;
    ruleId?: pulumi.Input<number>;
    subField?: pulumi.Input<string>;
}

export interface Ovh_iploadbalancing_tcp_farmProbe {
    forceSsl?: pulumi.Input<boolean>;
    interval?: pulumi.Input<number>;
    match?: pulumi.Input<string>;
    method?: pulumi.Input<string>;
    negate?: pulumi.Input<boolean>;
    pattern?: pulumi.Input<string>;
    port?: pulumi.Input<number>;
    type: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface Ovh_iploadbalancing_tcp_routeAction {
    target?: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface Ovh_iploadbalancing_tcp_routeRule {
    field?: pulumi.Input<string>;
    match?: pulumi.Input<string>;
    negate?: pulumi.Input<boolean>;
    pattern?: pulumi.Input<string>;
    ruleId?: pulumi.Input<number>;
    subField?: pulumi.Input<string>;
}

export interface Ovh_me_installation_templateCustomization {
    /**
     * @deprecated field is not used anymore
     */
    changeLog?: pulumi.Input<string>;
    customHostname?: pulumi.Input<string>;
    postInstallationScriptLink?: pulumi.Input<string>;
    postInstallationScriptReturn?: pulumi.Input<string>;
    /**
     * @deprecated field is not used anymore
     */
    rating?: pulumi.Input<number>;
    sshKeyName?: pulumi.Input<string>;
    useDistributionKernel?: pulumi.Input<boolean>;
}

export interface Ovh_vrackOrder {
    date?: pulumi.Input<string>;
    details?: pulumi.Input<pulumi.Input<inputs.Ovh_vrackOrderDetail>[]>;
    expirationDate?: pulumi.Input<string>;
    orderId?: pulumi.Input<number>;
}

export interface Ovh_vrackOrderDetail {
    description?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    orderDetailId?: pulumi.Input<number>;
    quantity?: pulumi.Input<string>;
}

export interface Ovh_vrackPlan {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_vrackPlanConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_vrackPlanConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface Ovh_vrackPlanOption {
    catalogName?: pulumi.Input<string>;
    configurations?: pulumi.Input<pulumi.Input<inputs.Ovh_vrackPlanOptionConfiguration>[]>;
    duration: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    pricingMode: pulumi.Input<string>;
}

export interface Ovh_vrackPlanOptionConfiguration {
    label: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

