// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh.Inputs
{

    public sealed class Ovh_cloud_project_containerregistryPlanGetArgs : Pulumi.ResourceArgs
    {
        [Input("code")]
        public Input<string>? Code { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("features")]
        private InputList<Inputs.Ovh_cloud_project_containerregistryPlanFeatureGetArgs>? _features;
        public InputList<Inputs.Ovh_cloud_project_containerregistryPlanFeatureGetArgs> Features
        {
            get => _features ?? (_features = new InputList<Inputs.Ovh_cloud_project_containerregistryPlanFeatureGetArgs>());
            set => _features = value;
        }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("registryLimits")]
        private InputList<Inputs.Ovh_cloud_project_containerregistryPlanRegistryLimitGetArgs>? _registryLimits;
        public InputList<Inputs.Ovh_cloud_project_containerregistryPlanRegistryLimitGetArgs> RegistryLimits
        {
            get => _registryLimits ?? (_registryLimits = new InputList<Inputs.Ovh_cloud_project_containerregistryPlanRegistryLimitGetArgs>());
            set => _registryLimits = value;
        }

        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public Ovh_cloud_project_containerregistryPlanGetArgs()
        {
        }
    }
}
