// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getCloudProjectContainerregistryUsers(args: GetCloudProjectContainerregistryUsersArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudProjectContainerregistryUsersResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getCloudProjectContainerregistryUsers:getCloudProjectContainerregistryUsers", {
        "registryId": args.registryId,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudProjectContainerregistryUsers.
 */
export interface GetCloudProjectContainerregistryUsersArgs {
    registryId: string;
    serviceName: string;
}

/**
 * A collection of values returned by getCloudProjectContainerregistryUsers.
 */
export interface GetCloudProjectContainerregistryUsersResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly registryId: string;
    readonly results: outputs.GetCloudProjectContainerregistryUsersResult[];
    readonly serviceName: string;
}

export function getCloudProjectContainerregistryUsersOutput(args: GetCloudProjectContainerregistryUsersOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCloudProjectContainerregistryUsersResult> {
    return pulumi.output(args).apply(a => getCloudProjectContainerregistryUsers(a, opts))
}

/**
 * A collection of arguments for invoking getCloudProjectContainerregistryUsers.
 */
export interface GetCloudProjectContainerregistryUsersOutputArgs {
    registryId: pulumi.Input<string>;
    serviceName: pulumi.Input<string>;
}
