// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCloudProjectRegions(args: GetCloudProjectRegionsArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudProjectRegionsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getCloudProjectRegions:getCloudProjectRegions", {
        "hasServicesUps": args.hasServicesUps,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudProjectRegions.
 */
export interface GetCloudProjectRegionsArgs {
    hasServicesUps?: string[];
    serviceName: string;
}

/**
 * A collection of values returned by getCloudProjectRegions.
 */
export interface GetCloudProjectRegionsResult {
    readonly hasServicesUps?: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly names: string[];
    readonly serviceName: string;
}

export function getCloudProjectRegionsOutput(args: GetCloudProjectRegionsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCloudProjectRegionsResult> {
    return pulumi.output(args).apply(a => getCloudProjectRegions(a, opts))
}

/**
 * A collection of arguments for invoking getCloudProjectRegions.
 */
export interface GetCloudProjectRegionsOutputArgs {
    hasServicesUps?: pulumi.Input<pulumi.Input<string>[]>;
    serviceName: pulumi.Input<string>;
}
