// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getIpService(args: GetIpServiceArgs, opts?: pulumi.InvokeOptions): Promise<GetIpServiceResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getIpService:getIpService", {
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpService.
 */
export interface GetIpServiceArgs {
    serviceName: string;
}

/**
 * A collection of values returned by getIpService.
 */
export interface GetIpServiceResult {
    readonly canBeTerminated: boolean;
    readonly country: string;
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ip: string;
    readonly organisationId: string;
    readonly routedTos: outputs.GetIpServiceRoutedTo[];
    readonly serviceName: string;
    readonly type: string;
}

export function getIpServiceOutput(args: GetIpServiceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIpServiceResult> {
    return pulumi.output(args).apply(a => getIpService(a, opts))
}

/**
 * A collection of arguments for invoking getIpService.
 */
export interface GetIpServiceOutputArgs {
    serviceName: pulumi.Input<string>;
}
