// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOvh_Dedicated_Server_Boots(args: GetOvh_Dedicated_Server_BootsArgs, opts?: pulumi.InvokeOptions): Promise<GetOvh_Dedicated_Server_BootsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getOvh_Dedicated_Server_Boots:getOvh_Dedicated_Server_Boots", {
        "bootType": args.bootType,
        "kernel": args.kernel,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getOvh_Dedicated_Server_Boots.
 */
export interface GetOvh_Dedicated_Server_BootsArgs {
    bootType?: string;
    kernel?: string;
    serviceName: string;
}

/**
 * A collection of values returned by getOvh_Dedicated_Server_Boots.
 */
export interface GetOvh_Dedicated_Server_BootsResult {
    readonly bootType?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly kernel?: string;
    readonly results: number[];
    readonly serviceName: string;
}

export function getOvh_Dedicated_Server_BootsOutput(args: GetOvh_Dedicated_Server_BootsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOvh_Dedicated_Server_BootsResult> {
    return pulumi.output(args).apply(a => getOvh_Dedicated_Server_Boots(a, opts))
}

/**
 * A collection of arguments for invoking getOvh_Dedicated_Server_Boots.
 */
export interface GetOvh_Dedicated_Server_BootsOutputArgs {
    bootType?: pulumi.Input<string>;
    kernel?: pulumi.Input<string>;
    serviceName: pulumi.Input<string>;
}
