// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getOvh_Order_Cart_Product_Options_Plan(args: GetOvh_Order_Cart_Product_Options_PlanArgs, opts?: pulumi.InvokeOptions): Promise<GetOvh_Order_Cart_Product_Options_PlanResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getOvh_Order_Cart_Product_Options_Plan:getOvh_Order_Cart_Product_Options_Plan", {
        "cartId": args.cartId,
        "catalogName": args.catalogName,
        "optionsPlanCode": args.optionsPlanCode,
        "planCode": args.planCode,
        "priceCapacity": args.priceCapacity,
        "product": args.product,
    }, opts);
}

/**
 * A collection of arguments for invoking getOvh_Order_Cart_Product_Options_Plan.
 */
export interface GetOvh_Order_Cart_Product_Options_PlanArgs {
    cartId: string;
    catalogName?: string;
    optionsPlanCode: string;
    planCode: string;
    priceCapacity: string;
    product: string;
}

/**
 * A collection of values returned by getOvh_Order_Cart_Product_Options_Plan.
 */
export interface GetOvh_Order_Cart_Product_Options_PlanResult {
    readonly cartId: string;
    readonly catalogName?: string;
    readonly exclusive: boolean;
    readonly family: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly mandatory: boolean;
    readonly optionsPlanCode: string;
    readonly planCode: string;
    readonly priceCapacity: string;
    readonly prices: outputs.GetOvh_Order_Cart_Product_Options_PlanPrice[];
    readonly product: string;
    readonly productName: string;
    readonly productType: string;
    readonly selectedPrices: outputs.GetOvh_Order_Cart_Product_Options_PlanSelectedPrice[];
}

export function getOvh_Order_Cart_Product_Options_PlanOutput(args: GetOvh_Order_Cart_Product_Options_PlanOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOvh_Order_Cart_Product_Options_PlanResult> {
    return pulumi.output(args).apply(a => getOvh_Order_Cart_Product_Options_Plan(a, opts))
}

/**
 * A collection of arguments for invoking getOvh_Order_Cart_Product_Options_Plan.
 */
export interface GetOvh_Order_Cart_Product_Options_PlanOutputArgs {
    cartId: pulumi.Input<string>;
    catalogName?: pulumi.Input<string>;
    optionsPlanCode: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    priceCapacity: pulumi.Input<string>;
    product: pulumi.Input<string>;
}
