// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getOrderCartProductOptionsPlan(args: GetOrderCartProductOptionsPlanArgs, opts?: pulumi.InvokeOptions): Promise<GetOrderCartProductOptionsPlanResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getOrderCartProductOptionsPlan:getOrderCartProductOptionsPlan", {
        "cartId": args.cartId,
        "catalogName": args.catalogName,
        "optionsPlanCode": args.optionsPlanCode,
        "planCode": args.planCode,
        "priceCapacity": args.priceCapacity,
        "product": args.product,
    }, opts);
}

/**
 * A collection of arguments for invoking getOrderCartProductOptionsPlan.
 */
export interface GetOrderCartProductOptionsPlanArgs {
    cartId: string;
    catalogName?: string;
    optionsPlanCode: string;
    planCode: string;
    priceCapacity: string;
    product: string;
}

/**
 * A collection of values returned by getOrderCartProductOptionsPlan.
 */
export interface GetOrderCartProductOptionsPlanResult {
    readonly cartId: string;
    readonly catalogName?: string;
    readonly exclusive: boolean;
    readonly family: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly mandatory: boolean;
    readonly optionsPlanCode: string;
    readonly planCode: string;
    readonly priceCapacity: string;
    readonly prices: outputs.GetOrderCartProductOptionsPlanPrice[];
    readonly product: string;
    readonly productName: string;
    readonly productType: string;
    readonly selectedPrices: outputs.GetOrderCartProductOptionsPlanSelectedPrice[];
}

export function getOrderCartProductOptionsPlanOutput(args: GetOrderCartProductOptionsPlanOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOrderCartProductOptionsPlanResult> {
    return pulumi.output(args).apply(a => getOrderCartProductOptionsPlan(a, opts))
}

/**
 * A collection of arguments for invoking getOrderCartProductOptionsPlan.
 */
export interface GetOrderCartProductOptionsPlanOutputArgs {
    cartId: pulumi.Input<string>;
    catalogName?: pulumi.Input<string>;
    optionsPlanCode: pulumi.Input<string>;
    planCode: pulumi.Input<string>;
    priceCapacity: pulumi.Input<string>;
    product: pulumi.Input<string>;
}
