// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOvh_Dbaas_Logs_Output_Graylog_Stream(args: GetOvh_Dbaas_Logs_Output_Graylog_StreamArgs, opts?: pulumi.InvokeOptions): Promise<GetOvh_Dbaas_Logs_Output_Graylog_StreamResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getOvh_Dbaas_Logs_Output_Graylog_Stream:getOvh_Dbaas_Logs_Output_Graylog_Stream", {
        "serviceName": args.serviceName,
        "title": args.title,
    }, opts);
}

/**
 * A collection of arguments for invoking getOvh_Dbaas_Logs_Output_Graylog_Stream.
 */
export interface GetOvh_Dbaas_Logs_Output_Graylog_StreamArgs {
    serviceName: string;
    title: string;
}

/**
 * A collection of values returned by getOvh_Dbaas_Logs_Output_Graylog_Stream.
 */
export interface GetOvh_Dbaas_Logs_Output_Graylog_StreamResult {
    readonly canAlert: boolean;
    readonly coldStorageCompression: string;
    readonly coldStorageContent: string;
    readonly coldStorageEnabled: boolean;
    readonly coldStorageNotifyEnabled: boolean;
    readonly coldStorageRetention: number;
    readonly coldStorageTarget: string;
    readonly createdAt: string;
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly indexingEnabled: boolean;
    readonly indexingMaxSize: number;
    readonly indexingNotifyEnabled: boolean;
    readonly isEditable: boolean;
    readonly isShareable: boolean;
    readonly nbAlertCondition: number;
    readonly nbArchive: number;
    readonly parentStreamId: string;
    readonly pauseIndexingOnMaxSize: boolean;
    readonly retentionId: string;
    readonly serviceName: string;
    readonly streamId: string;
    readonly title: string;
    readonly updatedAt: string;
    readonly webSocketEnabled: string;
}

export function getOvh_Dbaas_Logs_Output_Graylog_StreamOutput(args: GetOvh_Dbaas_Logs_Output_Graylog_StreamOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOvh_Dbaas_Logs_Output_Graylog_StreamResult> {
    return pulumi.output(args).apply(a => getOvh_Dbaas_Logs_Output_Graylog_Stream(a, opts))
}

/**
 * A collection of arguments for invoking getOvh_Dbaas_Logs_Output_Graylog_Stream.
 */
export interface GetOvh_Dbaas_Logs_Output_Graylog_StreamOutputArgs {
    serviceName: pulumi.Input<string>;
    title: pulumi.Input<string>;
}
