// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getOvh_Me_Installation_Template(args: GetOvh_Me_Installation_TemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetOvh_Me_Installation_TemplateResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getOvh_Me_Installation_Template:getOvh_Me_Installation_Template", {
        "templateName": args.templateName,
    }, opts);
}

/**
 * A collection of arguments for invoking getOvh_Me_Installation_Template.
 */
export interface GetOvh_Me_Installation_TemplateArgs {
    templateName: string;
}

/**
 * A collection of values returned by getOvh_Me_Installation_Template.
 */
export interface GetOvh_Me_Installation_TemplateResult {
    readonly availableLanguages: string[];
    readonly beta: boolean;
    readonly bitFormat: number;
    readonly category: string;
    readonly customizations: outputs.GetOvh_Me_Installation_TemplateCustomization[];
    readonly defaultLanguage: string;
    readonly deprecated: boolean;
    readonly description: string;
    readonly distribution: string;
    readonly family: string;
    readonly filesystems: string[];
    readonly hardRaidConfiguration: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly lastModification: string;
    readonly lvmReady: boolean;
    readonly partitionSchemes: outputs.GetOvh_Me_Installation_TemplatePartitionScheme[];
    readonly supportsDistributionKernel: boolean;
    readonly supportsGptLabel: boolean;
    readonly supportsRtm: boolean;
    readonly supportsSqlServer: boolean;
    readonly supportsUefi: string;
    readonly templateName: string;
}

export function getOvh_Me_Installation_TemplateOutput(args: GetOvh_Me_Installation_TemplateOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOvh_Me_Installation_TemplateResult> {
    return pulumi.output(args).apply(a => getOvh_Me_Installation_Template(a, opts))
}

/**
 * A collection of arguments for invoking getOvh_Me_Installation_Template.
 */
export interface GetOvh_Me_Installation_TemplateOutputArgs {
    templateName: pulumi.Input<string>;
}
