// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOrderCart(args: GetOrderCartArgs, opts?: pulumi.InvokeOptions): Promise<GetOrderCartResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ovh:index/getOrderCart:getOrderCart", {
        "description": args.description,
        "expire": args.expire,
        "ovhSubsidiary": args.ovhSubsidiary,
    }, opts);
}

/**
 * A collection of arguments for invoking getOrderCart.
 */
export interface GetOrderCartArgs {
    description?: string;
    expire?: string;
    ovhSubsidiary: string;
}

/**
 * A collection of values returned by getOrderCart.
 */
export interface GetOrderCartResult {
    readonly cartId: string;
    readonly description?: string;
    readonly expire: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly items: number[];
    readonly ovhSubsidiary: string;
    readonly readOnly: boolean;
}

export function getOrderCartOutput(args: GetOrderCartOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOrderCartResult> {
    return pulumi.output(args).apply(a => getOrderCart(a, opts))
}

/**
 * A collection of arguments for invoking getOrderCart.
 */
export interface GetOrderCartOutputArgs {
    description?: pulumi.Input<string>;
    expire?: pulumi.Input<string>;
    ovhSubsidiary: pulumi.Input<string>;
}
