// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class Ovh_cloud_project_user extends pulumi.CustomResource {
    /**
     * Get an existing Ovh_cloud_project_user resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Ovh_cloud_project_userState, opts?: pulumi.CustomResourceOptions): Ovh_cloud_project_user {
        return new Ovh_cloud_project_user(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ovh:index/ovh_cloud_project_user:ovh_cloud_project_user';

    /**
     * Returns true if the given object is an instance of Ovh_cloud_project_user.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ovh_cloud_project_user {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ovh_cloud_project_user.__pulumiType;
    }

    public /*out*/ readonly creationDate!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly openstackRc!: pulumi.Output<{[key: string]: any}>;
    public /*out*/ readonly password!: pulumi.Output<string>;
    public readonly roleName!: pulumi.Output<string | undefined>;
    public readonly roleNames!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly roles!: pulumi.Output<outputs.Ovh_cloud_project_userRole[]>;
    /**
     * Service name of the resource representing the id of the cloud project.
     */
    public readonly serviceName!: pulumi.Output<string>;
    public /*out*/ readonly status!: pulumi.Output<string>;
    public /*out*/ readonly username!: pulumi.Output<string>;

    /**
     * Create a Ovh_cloud_project_user resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Ovh_cloud_project_userArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Ovh_cloud_project_userArgs | Ovh_cloud_project_userState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Ovh_cloud_project_userState | undefined;
            inputs["creationDate"] = state ? state.creationDate : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["openstackRc"] = state ? state.openstackRc : undefined;
            inputs["password"] = state ? state.password : undefined;
            inputs["roleName"] = state ? state.roleName : undefined;
            inputs["roleNames"] = state ? state.roleNames : undefined;
            inputs["roles"] = state ? state.roles : undefined;
            inputs["serviceName"] = state ? state.serviceName : undefined;
            inputs["status"] = state ? state.status : undefined;
            inputs["username"] = state ? state.username : undefined;
        } else {
            const args = argsOrState as Ovh_cloud_project_userArgs | undefined;
            if ((!args || args.serviceName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'serviceName'");
            }
            inputs["description"] = args ? args.description : undefined;
            inputs["openstackRc"] = args ? args.openstackRc : undefined;
            inputs["roleName"] = args ? args.roleName : undefined;
            inputs["roleNames"] = args ? args.roleNames : undefined;
            inputs["serviceName"] = args ? args.serviceName : undefined;
            inputs["creationDate"] = undefined /*out*/;
            inputs["password"] = undefined /*out*/;
            inputs["roles"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
            inputs["username"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Ovh_cloud_project_user.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ovh_cloud_project_user resources.
 */
export interface Ovh_cloud_project_userState {
    creationDate?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    openstackRc?: pulumi.Input<{[key: string]: any}>;
    password?: pulumi.Input<string>;
    roleName?: pulumi.Input<string>;
    roleNames?: pulumi.Input<pulumi.Input<string>[]>;
    roles?: pulumi.Input<pulumi.Input<inputs.Ovh_cloud_project_userRole>[]>;
    /**
     * Service name of the resource representing the id of the cloud project.
     */
    serviceName?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Ovh_cloud_project_user resource.
 */
export interface Ovh_cloud_project_userArgs {
    description?: pulumi.Input<string>;
    openstackRc?: pulumi.Input<{[key: string]: any}>;
    roleName?: pulumi.Input<string>;
    roleNames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Service name of the resource representing the id of the cloud project.
     */
    serviceName: pulumi.Input<string>;
}
