// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class Ovh_ip_service extends pulumi.CustomResource {
    /**
     * Get an existing Ovh_ip_service resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Ovh_ip_serviceState, opts?: pulumi.CustomResourceOptions): Ovh_ip_service {
        return new Ovh_ip_service(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ovh:index/ovh_ip_service:ovh_ip_service';

    /**
     * Returns true if the given object is an instance of Ovh_ip_service.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ovh_ip_service {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ovh_ip_service.__pulumiType;
    }

    public /*out*/ readonly canBeTerminated!: pulumi.Output<boolean>;
    public /*out*/ readonly country!: pulumi.Output<string>;
    /**
     * Custom description on your ip
     */
    public readonly description!: pulumi.Output<string>;
    public /*out*/ readonly ip!: pulumi.Output<string>;
    /**
     * Details about an Order
     */
    public /*out*/ readonly orders!: pulumi.Output<outputs.Ovh_ip_serviceOrder[]>;
    public /*out*/ readonly organisationId!: pulumi.Output<string>;
    /**
     * Ovh Subsidiary
     */
    public readonly ovhSubsidiary!: pulumi.Output<string>;
    /**
     * Ovh payment mode
     */
    public readonly paymentMean!: pulumi.Output<string>;
    /**
     * Product Plan to order
     */
    public readonly plan!: pulumi.Output<outputs.Ovh_ip_servicePlan>;
    /**
     * Product Plan to order
     */
    public readonly planOptions!: pulumi.Output<outputs.Ovh_ip_servicePlanOption[] | undefined>;
    /**
     * Routage information
     */
    public /*out*/ readonly routedTos!: pulumi.Output<outputs.Ovh_ip_serviceRoutedTo[]>;
    public /*out*/ readonly serviceName!: pulumi.Output<string>;
    /**
     * Possible values for ip type
     */
    public /*out*/ readonly type!: pulumi.Output<string>;

    /**
     * Create a Ovh_ip_service resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Ovh_ip_serviceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Ovh_ip_serviceArgs | Ovh_ip_serviceState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Ovh_ip_serviceState | undefined;
            inputs["canBeTerminated"] = state ? state.canBeTerminated : undefined;
            inputs["country"] = state ? state.country : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["ip"] = state ? state.ip : undefined;
            inputs["orders"] = state ? state.orders : undefined;
            inputs["organisationId"] = state ? state.organisationId : undefined;
            inputs["ovhSubsidiary"] = state ? state.ovhSubsidiary : undefined;
            inputs["paymentMean"] = state ? state.paymentMean : undefined;
            inputs["plan"] = state ? state.plan : undefined;
            inputs["planOptions"] = state ? state.planOptions : undefined;
            inputs["routedTos"] = state ? state.routedTos : undefined;
            inputs["serviceName"] = state ? state.serviceName : undefined;
            inputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as Ovh_ip_serviceArgs | undefined;
            if ((!args || args.ovhSubsidiary === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ovhSubsidiary'");
            }
            if ((!args || args.paymentMean === undefined) && !opts.urn) {
                throw new Error("Missing required property 'paymentMean'");
            }
            if ((!args || args.plan === undefined) && !opts.urn) {
                throw new Error("Missing required property 'plan'");
            }
            inputs["description"] = args ? args.description : undefined;
            inputs["ovhSubsidiary"] = args ? args.ovhSubsidiary : undefined;
            inputs["paymentMean"] = args ? args.paymentMean : undefined;
            inputs["plan"] = args ? args.plan : undefined;
            inputs["planOptions"] = args ? args.planOptions : undefined;
            inputs["canBeTerminated"] = undefined /*out*/;
            inputs["country"] = undefined /*out*/;
            inputs["ip"] = undefined /*out*/;
            inputs["orders"] = undefined /*out*/;
            inputs["organisationId"] = undefined /*out*/;
            inputs["routedTos"] = undefined /*out*/;
            inputs["serviceName"] = undefined /*out*/;
            inputs["type"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Ovh_ip_service.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ovh_ip_service resources.
 */
export interface Ovh_ip_serviceState {
    canBeTerminated?: pulumi.Input<boolean>;
    country?: pulumi.Input<string>;
    /**
     * Custom description on your ip
     */
    description?: pulumi.Input<string>;
    ip?: pulumi.Input<string>;
    /**
     * Details about an Order
     */
    orders?: pulumi.Input<pulumi.Input<inputs.Ovh_ip_serviceOrder>[]>;
    organisationId?: pulumi.Input<string>;
    /**
     * Ovh Subsidiary
     */
    ovhSubsidiary?: pulumi.Input<string>;
    /**
     * Ovh payment mode
     */
    paymentMean?: pulumi.Input<string>;
    /**
     * Product Plan to order
     */
    plan?: pulumi.Input<inputs.Ovh_ip_servicePlan>;
    /**
     * Product Plan to order
     */
    planOptions?: pulumi.Input<pulumi.Input<inputs.Ovh_ip_servicePlanOption>[]>;
    /**
     * Routage information
     */
    routedTos?: pulumi.Input<pulumi.Input<inputs.Ovh_ip_serviceRoutedTo>[]>;
    serviceName?: pulumi.Input<string>;
    /**
     * Possible values for ip type
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Ovh_ip_service resource.
 */
export interface Ovh_ip_serviceArgs {
    /**
     * Custom description on your ip
     */
    description?: pulumi.Input<string>;
    /**
     * Ovh Subsidiary
     */
    ovhSubsidiary: pulumi.Input<string>;
    /**
     * Ovh payment mode
     */
    paymentMean: pulumi.Input<string>;
    /**
     * Product Plan to order
     */
    plan: pulumi.Input<inputs.Ovh_ip_servicePlan>;
    /**
     * Product Plan to order
     */
    planOptions?: pulumi.Input<pulumi.Input<inputs.Ovh_ip_servicePlanOption>[]>;
}
