// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Ovh_cloud_project_kube_nodepool extends pulumi.CustomResource {
    /**
     * Get an existing Ovh_cloud_project_kube_nodepool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Ovh_cloud_project_kube_nodepoolState, opts?: pulumi.CustomResourceOptions): Ovh_cloud_project_kube_nodepool {
        return new Ovh_cloud_project_kube_nodepool(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ovh:index/ovh_cloud_project_kube_nodepool:ovh_cloud_project_kube_nodepool';

    /**
     * Returns true if the given object is an instance of Ovh_cloud_project_kube_nodepool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ovh_cloud_project_kube_nodepool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ovh_cloud_project_kube_nodepool.__pulumiType;
    }

    /**
     * Enable anti affinity groups for nodes in the pool
     */
    public readonly antiAffinity!: pulumi.Output<boolean | undefined>;
    /**
     * Enable auto-scaling for the pool
     */
    public readonly autoscale!: pulumi.Output<boolean | undefined>;
    /**
     * Number of nodes which are actually ready in the pool
     */
    public /*out*/ readonly availableNodes!: pulumi.Output<number>;
    /**
     * Creation date
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Number of nodes present in the pool
     */
    public /*out*/ readonly currentNodes!: pulumi.Output<number>;
    /**
     * Number of nodes you desire in the pool
     */
    public readonly desiredNodes!: pulumi.Output<number>;
    /**
     * Flavor name
     */
    public /*out*/ readonly flavor!: pulumi.Output<string>;
    /**
     * Flavor name
     */
    public readonly flavorName!: pulumi.Output<string>;
    /**
     * Kube ID
     */
    public readonly kubeId!: pulumi.Output<string>;
    /**
     * Number of nodes you desire in the pool
     */
    public readonly maxNodes!: pulumi.Output<number>;
    /**
     * Number of nodes you desire in the pool
     */
    public readonly minNodes!: pulumi.Output<number>;
    /**
     * Enable monthly billing on all nodes in the pool
     */
    public readonly monthlyBilled!: pulumi.Output<boolean | undefined>;
    /**
     * NodePool resource name
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Project id
     */
    public /*out*/ readonly projectId!: pulumi.Output<string>;
    /**
     * Service name
     */
    public readonly serviceName!: pulumi.Output<string>;
    /**
     * Status describing the state between number of nodes wanted and available ones
     */
    public /*out*/ readonly sizeStatus!: pulumi.Output<string>;
    /**
     * Current status
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * Number of nodes with latest version installed in the pool
     */
    public /*out*/ readonly upToDateNodes!: pulumi.Output<number>;
    /**
     * Last update date
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;

    /**
     * Create a Ovh_cloud_project_kube_nodepool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Ovh_cloud_project_kube_nodepoolArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Ovh_cloud_project_kube_nodepoolArgs | Ovh_cloud_project_kube_nodepoolState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Ovh_cloud_project_kube_nodepoolState | undefined;
            inputs["antiAffinity"] = state ? state.antiAffinity : undefined;
            inputs["autoscale"] = state ? state.autoscale : undefined;
            inputs["availableNodes"] = state ? state.availableNodes : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["currentNodes"] = state ? state.currentNodes : undefined;
            inputs["desiredNodes"] = state ? state.desiredNodes : undefined;
            inputs["flavor"] = state ? state.flavor : undefined;
            inputs["flavorName"] = state ? state.flavorName : undefined;
            inputs["kubeId"] = state ? state.kubeId : undefined;
            inputs["maxNodes"] = state ? state.maxNodes : undefined;
            inputs["minNodes"] = state ? state.minNodes : undefined;
            inputs["monthlyBilled"] = state ? state.monthlyBilled : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["projectId"] = state ? state.projectId : undefined;
            inputs["serviceName"] = state ? state.serviceName : undefined;
            inputs["sizeStatus"] = state ? state.sizeStatus : undefined;
            inputs["status"] = state ? state.status : undefined;
            inputs["upToDateNodes"] = state ? state.upToDateNodes : undefined;
            inputs["updatedAt"] = state ? state.updatedAt : undefined;
        } else {
            const args = argsOrState as Ovh_cloud_project_kube_nodepoolArgs | undefined;
            if ((!args || args.flavorName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'flavorName'");
            }
            if ((!args || args.kubeId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'kubeId'");
            }
            if ((!args || args.serviceName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'serviceName'");
            }
            inputs["antiAffinity"] = args ? args.antiAffinity : undefined;
            inputs["autoscale"] = args ? args.autoscale : undefined;
            inputs["desiredNodes"] = args ? args.desiredNodes : undefined;
            inputs["flavorName"] = args ? args.flavorName : undefined;
            inputs["kubeId"] = args ? args.kubeId : undefined;
            inputs["maxNodes"] = args ? args.maxNodes : undefined;
            inputs["minNodes"] = args ? args.minNodes : undefined;
            inputs["monthlyBilled"] = args ? args.monthlyBilled : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["serviceName"] = args ? args.serviceName : undefined;
            inputs["availableNodes"] = undefined /*out*/;
            inputs["createdAt"] = undefined /*out*/;
            inputs["currentNodes"] = undefined /*out*/;
            inputs["flavor"] = undefined /*out*/;
            inputs["projectId"] = undefined /*out*/;
            inputs["sizeStatus"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
            inputs["upToDateNodes"] = undefined /*out*/;
            inputs["updatedAt"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Ovh_cloud_project_kube_nodepool.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ovh_cloud_project_kube_nodepool resources.
 */
export interface Ovh_cloud_project_kube_nodepoolState {
    /**
     * Enable anti affinity groups for nodes in the pool
     */
    antiAffinity?: pulumi.Input<boolean>;
    /**
     * Enable auto-scaling for the pool
     */
    autoscale?: pulumi.Input<boolean>;
    /**
     * Number of nodes which are actually ready in the pool
     */
    availableNodes?: pulumi.Input<number>;
    /**
     * Creation date
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Number of nodes present in the pool
     */
    currentNodes?: pulumi.Input<number>;
    /**
     * Number of nodes you desire in the pool
     */
    desiredNodes?: pulumi.Input<number>;
    /**
     * Flavor name
     */
    flavor?: pulumi.Input<string>;
    /**
     * Flavor name
     */
    flavorName?: pulumi.Input<string>;
    /**
     * Kube ID
     */
    kubeId?: pulumi.Input<string>;
    /**
     * Number of nodes you desire in the pool
     */
    maxNodes?: pulumi.Input<number>;
    /**
     * Number of nodes you desire in the pool
     */
    minNodes?: pulumi.Input<number>;
    /**
     * Enable monthly billing on all nodes in the pool
     */
    monthlyBilled?: pulumi.Input<boolean>;
    /**
     * NodePool resource name
     */
    name?: pulumi.Input<string>;
    /**
     * Project id
     */
    projectId?: pulumi.Input<string>;
    /**
     * Service name
     */
    serviceName?: pulumi.Input<string>;
    /**
     * Status describing the state between number of nodes wanted and available ones
     */
    sizeStatus?: pulumi.Input<string>;
    /**
     * Current status
     */
    status?: pulumi.Input<string>;
    /**
     * Number of nodes with latest version installed in the pool
     */
    upToDateNodes?: pulumi.Input<number>;
    /**
     * Last update date
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Ovh_cloud_project_kube_nodepool resource.
 */
export interface Ovh_cloud_project_kube_nodepoolArgs {
    /**
     * Enable anti affinity groups for nodes in the pool
     */
    antiAffinity?: pulumi.Input<boolean>;
    /**
     * Enable auto-scaling for the pool
     */
    autoscale?: pulumi.Input<boolean>;
    /**
     * Number of nodes you desire in the pool
     */
    desiredNodes?: pulumi.Input<number>;
    /**
     * Flavor name
     */
    flavorName: pulumi.Input<string>;
    /**
     * Kube ID
     */
    kubeId: pulumi.Input<string>;
    /**
     * Number of nodes you desire in the pool
     */
    maxNodes?: pulumi.Input<number>;
    /**
     * Number of nodes you desire in the pool
     */
    minNodes?: pulumi.Input<number>;
    /**
     * Enable monthly billing on all nodes in the pool
     */
    monthlyBilled?: pulumi.Input<boolean>;
    /**
     * NodePool resource name
     */
    name?: pulumi.Input<string>;
    /**
     * Service name
     */
    serviceName: pulumi.Input<string>;
}
