// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Ovh_domain_zone_record extends pulumi.CustomResource {
    /**
     * Get an existing Ovh_domain_zone_record resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Ovh_domain_zone_recordState, opts?: pulumi.CustomResourceOptions): Ovh_domain_zone_record {
        return new Ovh_domain_zone_record(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ovh:index/ovh_domain_zone_record:ovh_domain_zone_record';

    /**
     * Returns true if the given object is an instance of Ovh_domain_zone_record.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ovh_domain_zone_record {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ovh_domain_zone_record.__pulumiType;
    }

    public readonly fieldtype!: pulumi.Output<string>;
    public readonly subdomain!: pulumi.Output<string | undefined>;
    public readonly target!: pulumi.Output<string>;
    public readonly ttl!: pulumi.Output<number | undefined>;
    public readonly zone!: pulumi.Output<string>;

    /**
     * Create a Ovh_domain_zone_record resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Ovh_domain_zone_recordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Ovh_domain_zone_recordArgs | Ovh_domain_zone_recordState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Ovh_domain_zone_recordState | undefined;
            inputs["fieldtype"] = state ? state.fieldtype : undefined;
            inputs["subdomain"] = state ? state.subdomain : undefined;
            inputs["target"] = state ? state.target : undefined;
            inputs["ttl"] = state ? state.ttl : undefined;
            inputs["zone"] = state ? state.zone : undefined;
        } else {
            const args = argsOrState as Ovh_domain_zone_recordArgs | undefined;
            if ((!args || args.fieldtype === undefined) && !opts.urn) {
                throw new Error("Missing required property 'fieldtype'");
            }
            if ((!args || args.target === undefined) && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            if ((!args || args.zone === undefined) && !opts.urn) {
                throw new Error("Missing required property 'zone'");
            }
            inputs["fieldtype"] = args ? args.fieldtype : undefined;
            inputs["subdomain"] = args ? args.subdomain : undefined;
            inputs["target"] = args ? args.target : undefined;
            inputs["ttl"] = args ? args.ttl : undefined;
            inputs["zone"] = args ? args.zone : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Ovh_domain_zone_record.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ovh_domain_zone_record resources.
 */
export interface Ovh_domain_zone_recordState {
    fieldtype?: pulumi.Input<string>;
    subdomain?: pulumi.Input<string>;
    target?: pulumi.Input<string>;
    ttl?: pulumi.Input<number>;
    zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Ovh_domain_zone_record resource.
 */
export interface Ovh_domain_zone_recordArgs {
    fieldtype: pulumi.Input<string>;
    subdomain?: pulumi.Input<string>;
    target: pulumi.Input<string>;
    ttl?: pulumi.Input<number>;
    zone: pulumi.Input<string>;
}
